# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14eO8R2v2GfNjZsbLleJ4rlBbtviae9R-
"""

import statistics as st

x = [1, 2, 3, 4, 5]
y = [2, 3, 4, 5, 6]
media_x = st.mean(x)
media_y = st.mean(y)

varianca=sum((x[i]-media_x)**2 for i in range(len(x)))
covarianca=sum((x[i]-media_x)*(y[i]-media_y) for i in range(len(x)))

#Coeficiente de Inclinaçao
b1 = covarianca / varianca
#Coeficiente de Intercepto
b0 = media_y-b1*media_x

print(b0)