# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QC-MAFVoYg-WU76PLzMWYLrFJFsvkJ-U
"""

import pandas as pd
import matplotlib.pyplot as plt

california_h_df = pd.read_csv('/content/california_housing_train.csv')

print(california_h_df)

display(california_h_df.head(5))

df2=pd.DataFrame(california_h_df,columns=['latitude','total_rooms','population'])

print(df2)

import matplotlib.pyplot as plt

fig, ax = plt.subplots()

california = ['latitude', 'total_rooms ', 'population']
counts = [10, 20,30]
bar_labels = ['red', 'blue',  'orange']
bar_colors = ['tab:blue', 'tab:red', 'tab:orange']

ax.bar(california, counts, label=bar_labels, color=bar_colors)

ax.set_ylabel('california supply')
ax.set_title('California')
ax.legend(title='California color')

plt.show()