# -*- coding: utf-8 -*-
"""07_Exercícios_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxMSUIkhzHDPDzWwZkDRHqU0O7vHtPQv

#Pandas
###Python para Data Science
###Aula 7
###Msc. Ailton Santos

Escreva um código que receba como entrada o nome, ou parte do nome, de um jogo, e que imprima ao usuário os jogos encontrados, bem como sua plataforma, ano, gênero e publicador.


O programa deve aceitar diferentes formas de escrita. Por exemplo, caso o usuário digite "mAriO", o programa deve devolver todos os jogos que contém "mario" no nome.

Os valores impressos do nome dos jogos devem estar em formato de título, isso é, apenas as primeiras letras de cada palavra em maiúsculo.

Faça uso da base de dados disponível em https://go.aws/3at1x9T e use o Pandas na resolução do exercício
"""

import pandas as pd

# Carregar o dataset de jogos
url = 'https://go.aws/3at1x9T'
df = pd.read_csv(url)

# Normalizar os dados para facilitar a busca
df['name_normalized'] = df['name'].str.lower()

# Solicitar ao usuário o nome ou parte do nome do jogo
search_term = input("Digite o nome ou parte do nome do jogo: ").lower()

# Filtrar os jogos que contêm o termo de busca
filtered_df = df[df['name_normalized'].str.contains(search_term)]

# Verificar se há resultados
if not filtered_df.empty:
    # Exibir os resultados formatados
    print("\nJogos encontrados:")
    for _, row in filtered_df.iterrows():
        print(f"Nome: {row['name'].title()}")
        print(f"Plataforma: {row['platform']}")
        print(f"Ano: {row['year']}")
        print(f"Gênero: {row['genre']}")
        print(f"Publicador: {row['publisher']}")
        print("-" * 40)
else:
    print("Nenhum jogo encontrado com esse nome.")