# -*- coding: utf-8 -*-
"""06_Intro_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fo9btHq9ijOEXIHwVBqSi2xDYdevTJlq

#Demonstração Pandas
###Python para Data Science
###Aula 6
###Msc. Ailton Santos

#Importar Bibliotecas
"""

import pandas as pd
import numpy as np

"""#Series (observe o índice do lado esquerdo)"""

s1=pd.Series([1,2,-5,0])

s1

s1.values

s1.index

s2=pd.Series([1,2,-5,0], index=['a','b', 'c', 'd'])

s2

s2.index

s2['a']=1000

s2

"""#Comparação"""

s2[s2>0]

"""#Algebra"""

s2*2

s2

s2.isnull()

"""#Dataframe

#Criar Dataframe
"""

dados={'estado':['SP', 'MG','PR','SP','MG','PR'],
       'ano':[2019, 2019,2019, 2020,2020,2020],
       'pop':[45.9, 21.2,16.9,46.6,21.4,17.3]}
df1=pd.DataFrame(dados)

df1

df1.head(2)

"""#Visualizar partes Dataframe

"""

df1.tail(2)

df1.sample(2)



"""#Novo DF a partir o anterior (veja as colunas)"""

df2=pd.DataFrame(dados,columns=['ano','estado','pop'])

df2

"""#Observar DF"""

df2['estado']

df2.ano

df2.dtypes

"""#Atribuir Valores"""

df2['estimativa']=50

df2

df2['estimativa']=np.arange(6)

df2

df3=df2

df3

df3=df2['ano']

df3

df2['Não Paraná']=df2.estado!='PR'

df2

"""#Excluir Coluna"""

del df2['Não Paraná']

df2

"""#Entender o DataFrame"""

df2.shape

df2.shape[0]

df2.index

df2.columns

df2.count()

"""#Alterar Informação das Colunas"""

df2.columns=['Ano','estado','Populacao','estimativa']

df2

"""#Analisar o DataFrame"""

df2.describe(include='all')

"""#Alterar valores e  consultar dados"""

df2['Ano']=df2['Ano']+2

df2

df2[df2['Ano']>2021]

df4=df2[df2['Ano']>2021]

df4

"""#Excluir Colunas"""

df4.drop('Ano', axis='columns')

df4

df2

df2.drop('Ano', axis='columns', inplace=True)

df2

"""#Excluir Linhas"""

df2.drop([0,1])

df2

"""###Observe a propagação na exclusão definitiva"""

dflinhas=df2

dflinhas.drop([0,1],inplace=True)

dflinhas

df2

"""#Ver Dados de linhas"""

df2.iloc[0]

df2.iloc[1:3]

df2.iloc[1:3,[1,2]]

df2

