# -*- coding: utf-8 -*-
"""Numpy+Matplolib+Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1en2MXkM35iQnz27jt2Zs90z56_EfHBkR
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

nome_arquivo_csv="precos_imoveis.csv"

df1=pd.read_csv(nome_arquivo_csv)

print(df1.describe())

print(df1.info())

print(df1.head())

df1.head(10)

ano_mean=df1['ano_construcao'].mean()

print(ano_mean)

preco_std=df1['preco'].std()

print(preco_std)

preco_max=df1['preco'].max()

print(preco_max)

preco_min=df1['preco'].min()

print(preco_min)

#Histograma da ditribuição dos preços
plt.figure(figsize=(10,6))
sns.histplot(df1['preco'],kde=True)
plt.xlabel('Preço')
plt.ylabel('Frequência')
plt.title('Distribuição dos Preços dos Imóveis')
plt.show()

''' Como ficaria este Histograma com o Matplotlib? '''