# -*- coding: utf-8 -*-
"""08_Intro_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sXhkf2ij3wmlIsZv5Q0OeclJ5fK572l

##Matplotlib
##Python para Data Science
##Aula 08
##Msc. Ailton J. Santos
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(50)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 200, where=(ys > 200), facecolor='b', alpha=0.01)

plt.title("Análise Randomica")
plt.show()

"""###Utilização da Biblioteca Matplotlib"""

import numpy as np

import matplotlib.pyplot as plt

"""Matplotlib é uma biblioteca de software para criação de gráficos e visualizações de dados em geral, feita para e da linguagem de programação Python e sua extensão de matemática NumPy."""

# Dados para o gráfico de linha
x = [1, 2, 3, 4, 5]

y = [2, 4, 6, 8, 10]

# Criar o gráfico de linha
plt.plot(x, y)

# Adicionar rótulos aos eixos x e y
plt.xlabel('Eixo X')

plt.ylabel('Eixo Y')

# Adicionar título ao gráfico
plt.title('Gráfico de Linha Simples')

# Exibir o gráfico
plt.show()

