# -*- coding: utf-8 -*-
"""AlunosFaltas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXzIvk3rA_qttlZg3oHIVR3Xw8HvjM4N
"""

TotalHoras=float(input('Digite a qtd de Horas do Curso: '))

TotalFaltas=(TotalHoras*25)/100

print(TotalFaltas)

QtdFaltas=float(input('Digite a qtd de Horas que vc faltou: '))

if QtdFaltas<=TotalFaltas:
  print('Você está aprovado, boa sorte! As faltas permitidas são', TotalFaltas)
else:
  print('Reprovado')