# -*- coding: utf-8 -*-
"""Aula 4 - numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNo-tIEHnYA2J7zeP0fZpNKUrU8-bG3t
"""

import numpy as np

#Matriz unidimensional
mt=np.array([12,34,26,18,10])

print(mt)

print(type(mt))

#criar uma array com um tipo específico
mtfloat=np.array([1,2,3],dtype=np.float64)

print(mtfloat)

print(type(mtfloat))

#transformar dados das arrays
mtnew=np.array([1.4,3.6,-5.1,9.42,4.999999])

print(mtnew)

mtnewint=mtnew.astype(np.int32)

print(mtnewint)

#fazendo a transformação inversa

mtmarcha=np.array([1,2,3,4])

print(mtmarcha)

mtnaosei=mtmarcha.astype(np.float64)

print(mtnaosei)

#Matriz Bidimensional
mtjoao=np.array([[7,23,2],[12,27,4],[5,34,23]])

print(mtjoao)

print(mtjoao[1][2])

#Matriz 'Empty'
mttha=np.empty([3,2],dtype=int)

print(mttha)

#Matriz com elemento definido
elementdef=np.ones([5,7])

print(elementdef)

#Matriz com elementos random
fran=np.random.random((5))

print(fran)

#Outra forma para elementos aleatórios
f3s=np.random.default_rng(1)

print(f3s)

f2s=f3s.random(3)

print(f2s)

#removendo repetições
removrep=np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
removrep=np.unique(removrep)

print(removrep)

print(removrep[3])