# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQOk7pcbTo8ov7lZPGzg_rpJnk0JJt-s
"""

#percentual que pode faltar
total_horas=int(input('Digite a quantidade de horas do curso:'))

total_faltas = (total_horas * 25) / 100
print("Total de faltas permitidas:", total_faltas)

qtd_faltas = float(input("Digite a quantidade de horas que você faltou: "))

if qtd_faltas <= total_faltas:
    print("Você está aprovado! As faltas permitidas são", total_faltas)
else:
    print("Reprovado")