# -*- coding: utf-8 -*-
"""aula 2 primeiro atividade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crQbFfl2i68YQvk0flK-AfP7DnQ9cGOz
"""

#Definindo a temperatura
temp=int(input('digite a temperatura: '))

#avaliar se temperatura
if temp <10:
  print('está frio! :(')
elif temp >=10 and temp <=20:
    print('está frio, mas dá :')
elif temp >=20 and temp <27:
      print('agora sim!')
 else:
     print('está muito quente')