# -*- coding: utf-8 -*-
"""aula 2 segunda atividade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZYXyAMqC9NmATtghYOwaXWH7KXjkG54
"""

totalHoras=int(input('digite a quantidade de de aulas: '))

totalFaltas=(totalHoras*25)/100

print(totalHoras)

Qtdfaltas=float(in)