# -*- coding: utf-8 -*-
"""Biblioteca Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ll055Q70Lrqj8-hVCkyM59JPcJNuvp-C

# Nova seção
"""

import statistics
dados = [1, 2, 3, 2, 1, 1, 2, 3, 2, 2]
moda = statistics.mode(dados)
print("A maioria dos alunos come pizza", moda, "vezes por semana.")

import statistics
numeros=[60, 70, 80, 90, 100]

# Calcular a média
media = sum(numeros) / len(numeros)
desvio_padrao_amostra = statistics.stdev(numeros)
desvio_padrao = statistics.stdev(numeros)
print("Desvio padrão da amostra:", desvio_padrao_amostra)
print("Desvio padrão da população:", desvio_padrao, media)
print("A média é:", media)

import statistics
tempo_atleta=[10, 15, 20, 25, 30]
tempo_medio = sum(tempo_atleta) / len(tempo_atleta)
nelhor_tempo = min(tempo_atleta)
print(f"O tempo médio que o atleta levou para completar as corridas é: {tempo_medio} minutos.")
print(f"O melhor tempo que o atleta obteve foi: {tempo_atleta} minutos.")

import statistics
tempos = [10, 15, 20, 25, 30]
tempo_medio = sum(tempos) / len(tempos)
melhor_tempo = min(tempos)
print(f"O tempo médio que o atleta levou para completar as corridas é: {tempo_medio} minutos.")
print(f"O melhor tempo que o atleta obteve foi: {melhor_tempo} minutos.")