# -*- coding: utf-8 -*-
"""BibloStatic3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWq54l_M1iwXH8cj3giRCLjggYGxHSRm
"""

import statistics as st
import math as mt
dados = [10, 15, 20, 25, 30, 35, 40, 45, 50]
#Soma de todos elementos divido pelo numero (qtd) de elementos
media = st.mean(dados)

#median
mediana = st.median(dados)

#moda
moda = st.mode(dados)

print('Conjunto de Dados:', dados)
print('Media:', media)
print('Mediana:', mediana)
print('Moda:', moda)