# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wF58BdR4-QOGYBT_dLLUHmpaeI1eCfZU
"""

import statistics as st
# Dados de consumo de energia em kWh
consumo_energia = ([20, 25, 30, 35, 40])

# Calculando a média
media = st.mean(consumo_energia)

# Calculando a variância
variancia = st.mean(consumo_energia)

# Exibindo os resultados
print(f"Média do consumo de energia: {media} kWh")
print(f"Variância do consumo de energia: {variancia} kWh^2")