# -*- coding: utf-8 -*-
"""estatistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzjvxWC4DTtRxlHVrkhLDJu2KNbJdEJf
"""



mediana= st.median(dados)

moda= st.mode(dados)

print('conjunto de dados',dados)
print('média:,media')
print('mediana:,mediana')
print('Moda:',moda)