# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIs1guUch2XgwRcnPpLO_p34s1oqpznN
"""

temp = int (input ('digite a temperatura:'))

if temp <10:
  print ('Esta frio!')
elif temp >=10 and temp <20:
  print ('Esta frio , mas dá!')
elif temp >=20 and temp <34:
  print ('Agora sim!')
else: print ('Está muito quente')

