# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTZODk9X2AeoFtLcbCtn8PtuZxlltT6X
"""

TotalHoras = float(input('Digitea qtde de horas do curso:'))

TotalFaltas=(TotalHoras *25)/100
print(TotalFaltas)
QtdeFaltas=float(input('Digite a qtde de horas que vc faltou:'))
if QtdeFaltas<=TotalFaltas:
  print ('Você esta aprovado,boa sorte! As faltas permitidas são:',TotalFaltas)
else:
  print('Reprovado')