# -*- coding: utf-8 -*-
"""horas de estudo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msIMmjLfqQl1CW0PwfnCRlAkq_q4tbPm
"""

import statistics as st

horas_estudo=[5,7,3,8,6,4,9,5,7,6]

notas=[75,85,60,90,80,70,95,75,85,80]

correlacao=st.correlation(horas_estudo, notas)

print(correlacao)