# -*- coding: utf-8 -*-
"""PairNumbs.CountHigLowValue.TempAverage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jxrk9sFw2GaNzUOiLhV4xAcTr0rX1OwG
"""

numeros = [1, 2, 3, 10, 12]

for francio in numeros:
    if francio == 10:
        break
    print(francio)
else:
    print('Acabou')

for numero in [0, 18, 56, 77, 95]:
  print(numero)
else:
    print("Acabou")

"""#programing using commands in which finds pair numbs between 1 to 100
numeros = [1,100,2]
"""

numeros = [1,101,2]

for numeros in range(0,101,2):
  print(numeros)

"""faça um programa em python (utilize a estrutura for) que leia 10 valores inteiros e : encontre e mostre o maior valor

"""

maior_valor = None
for i in range (10):
  valor = int(input(f"Digite o {i+1}º valor inteiro: "))
  if maior_valor is None or valor > maior_valor:
        maior_valor = valor
print("O maior valor digitado é:", maior_valor)

"""Agora encontre e mostre o menor valor"""

menor_valor = None
for i in range (10):
  valor = int(input(f"Digite o {i+1}º valor inteiro: "))
  if menor_valor is None or valor < menor_valor:
        menor_valor = valor
print("O menor valor digitado é:", menor_valor)

"""Agora Calcule e mostre a média dos numeros lidos"""

soma = 0
for i in range (10):
  valor = int(input(f"Digite o {i+1}º valor inteiro: "))
  soma += valor
  valor = soma / 10
  print("A média de somatório é:", valor)

"""Faça um programa em linguagem Python que recebe a temperaturade z cliente e imprima a mensagem de se a temperatura está normal (menor que 37,2°C) ou está em estado febril (37,3°C a 38°C) ou com febre (38°C a 39°C) ou ainda se febre alta (acima de 39°C)."""

TempNormal = 37.2

TempNormal = float(input('Digite sua temperatura: '))

if TempNormal <37.2:
  print("Sua Temperatura está Normal. Parabéns! continue se cuidando.")
elif 37.3<= TempNormal <38:
  print("Você está em estado febril, fique em alerta!")
elif 38<= TempNormal <=39:
  print('Você está com febre, procure ajuda urgente!')
elif TempNormal >39:
  print('Você está com febre alta, procure um médico para diagnóstico urgente!')

""""PESSOAS ANALISADAS E MÉDIA" = Agora, Faça um programa em linguagem Python que recebe a temperaturade z cliente e imprima a mensagem de se a temperatura está normal (menor que 37,2°C) ou está em estado febril (37,3°C a 38°C) ou com febre (38°C a 39°C) ou ainda se febre alta (acima de 39°C). No final mostre a quantidade de pessoas analisadas e a média de temperatura.:"""

qtde_pessoas = int(input('Digite o numero de pessoas que deseja analisar:'))
soma_temp = 0

for i in range(qtde_pessoas):
  temperatura = float(input(f'Digite a temperatura da {i+1}ª pessoa: '))

soma_temp += temperatura

if TempNormal <37.2:
  print("Sua Temperatura está Normal. Parabéns! continue se cuidando.")
elif 37.3<= TempNormal <38:
  print("Você está em estado febril, fique em alerta!")
elif 38<= TempNormal <=39:
  print('Você está com febre, procure ajuda urgente!')
elif TempNormal >39:
  print('Você está com febre alta, procure um médico para diagnóstico urgente!')

#Resultado total das pessoas analisadas
media_temp = soma_temp / qtde_pessoas
print(f"\nTotal de Pessoas Analisadas: {qtde_pessoas}")

#Resultado media das temperaturas
media_temp = soma_temp / qtde_pessoas
print(f"\nTotal de Pessoas Analisadas: {qtde_pessoas}")
print(f"\nMedia de Temperaturas das pessoas Analisadas: {media_temp}")

#Resultado Media das temp em ºC
media_temp = soma_temp / qtde_pessoas
print(f"\nTotal de Pessoas Analisadas: {qtde_pessoas}")
print(f"Media de Temperaturas das pessoas Analisadas: {media_temp:.2f}°C")