# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doxAri1yZsAX6aXVvLQLMkVoWPgy77m1
"""

import pandas as pd
import numpy as np

jogos = [
    {"nome": "Super Mario Bros.", "plataforma": "NES", "ano": 1985, "gênero": "Plataforma", "publicador": "Nintendo"},
]

def imprimir_jogos_por_nome(parte_nome):
    encontrados = []
    for jogo in jogos:
        if parte_nome.lower() in jogo['nome'].lower():
            encontrados.append(jogo)

    if encontrados:
        for jogo in encontrados:
            print(f"Nome: {jogo['nome'].title()}")
            print()
    else:
        print("Nenhum jogo encontrado.")
parte_nome = input("Digite o nome, ou parte do nome, do jogo: ")
imprimir_jogos_por_nome(parte_nome)