# -*- coding: utf-8 -*-
"""quantidade de faltas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsIuafnHbR5Egp6Qo8-EjkgTnHAi1lG5
"""

totalhoras=float(input('Digite a quantidade de horas do curso '))

Totalfaltas=(totalhoras*25)/100

print(Totalfaltas)

qtdfaltas=float(input('Digite a quantidade de horas que você faltou: '))

if  qtdfaltas <= Totalfaltas:
  print('você está aprovado, boa sorte! As faltas permitidas são', Totalfaltas)
else:
  print('reprovado')