# -*- coding: utf-8 -*-
"""statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_I9zWt0ni4HFM4Q6HafzMBRsaeP3zD8A
"""

import statistics as st
import math as mt
dados = [10, 15, 20, 25, 30, 35, 40, 45, 50]

#Soma de todos elementos dividido pela quantidade de elementos dividido pela quantidade de elementos
media = st.mean(dados)

#Mediana
mediana = st.median(dados)

#Moda
moda = st.mode(dados)

print('Conjunto de dados', dados)
print('Média:', media)
print('Mediana:', mediana)
print('Moda:', moda)

"""EXERCISE NUMB 2"""

import statistics as st
notas = [7.5, 8.2, 6.9, 9.5, 5.8, 7.1, 8.6, 6.3, 9.0, 8.8]

#a medida que vc se distancia da amostra, aumenta a margem de erro
#se vc reduz a população ou quantidade, aumenta sua margem de erro

#Media
media = st.mean(notas)

#Mediana
mediana = st.median(notas)

#Moda
moda = st.mode(notas)

#Desvio Padrao
desvio_padrao = st.stdev(notas)

print('Listagem das Notas:', notas)
print('Valor da média:', media)
print('Mediana:', mediana)
print('Moda:', moda)
print('Valor do desvio padrão:', desvio_padrao)

"""EXERCISE NUMBER 3 = CORRELAÇÃO"""

import statistics as st

horas_estudo =[5, 7, 3, 8, 6, 4, 9, 5, 7, 6]

notas = [75, 85, 60, 90, 80, 70, 95, 75, 85, 80]

#Calcul correlacao entre duas variaveis
correlacao = st.correlation(horas_estudo, notas)

print(correlacao)

"""EXERCISE NUMBER 4 . Imagine que você está estudando o tempo que leva para os
alunos/funcionários chegarem ao SENAI e qual seria o meio de trasnporte
a. Metrô/Trem
b. Carro
c. Moto
d. Outro
Anote o tempo (em minutos) que cada aluno leva para chegar
à escola e:
a. Metrô/Trem
b. Carro
c. Moto
d. Outro
e.tempo mediano que os alunos levam para chegar à escola.
f.Comente se poderia ter diferença nestes tempos estaria correto ou não incluir
o tempo mediano

"""

import statistics as st

import math as mt

minutos_viagem = [98, 70, 80, 60, 120, 80, 110, 120, 15, 40, 80, 100, 120, 20, 30, 35]

#Relacao dos meios transporte
metro = 1
trem = 2
onibus = 3
carro = 4
moto = 5
ape = 6

meios_transporte = [trem, carro, onibus, metro, trem, carro, trem, onibus, ape, metro, trem, moto, carro, ape, ape, trem]

#Correlacao
correlacao = st.correlation(minutos_viagem, meios_transporte)

print('O valor de correlacao é de:', correlacao)

"""AGORA VAMOS ACHAR O TEMPO MEDIANO"""

#Media
media = st.mean(minutos_viagem)

#Mediana
mediana = st.median(minutos_viagem)

#Moda
moda = st.mode(meios_transporte)

#Desvio Padrao
desvio_padrao = st.stdev(minutos_viagem)

print(f"O tempo medio que levam para chegar no Senai é de:', {media:.2f} minutos")
print("\n")
print('A mediana de tempo é:', mediana)
print('O tempo pra chegar ao Senai que mais se repete é:', moda)
print('O valor de desvio padrão é:', desvio_padrao)

