# -*- coding: utf-8 -*-
"""statistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145jsnFEVEL92QNOUnHa_TgmuTq0XawXW
"""

import statistics as st

import math as mt

minutos_viagem = [98, 70, 80, 60, 120, 80, 110, 120, 15, 40, 80, 100, 120, 20, 30, 35]

#Relacao dos meios transporte
metro = 1
trem = 2
onibus = 3
carro = 4
moto = 5
ape = 6

meios_transporte = [trem, carro, onibus, metro, trem, carro, trem, onibus, ape, metro, trem, moto, carro, ape, ape, trem]

#Correlacao
correlacao = st.correlation(minutos_viagem, meios_transporte)

print('O valor de correlacao é de:', correlacao)

"""

```
# Isto está formatado como código
```

EXERCISE NUMB 2 TEMPO MEDIANO"""

#Media
media = st.mean(minutos_viagem)

#Mediana
mediana = st.median(minutos_viagem)

#Moda
moda = st.mode(meios_transporte)

#Desvio Padrao
desvio_padrao = st.stdev(minutos_viagem)

print(f"O tempo medio que levam para chegar no Senai é de:', {media:.2f} minutos")
print("\n")
print('A mediana de tempo é:', mediana)
print('O tempo pra chegar ao Senai que mais se repete é:', moda)
print('O valor de desvio padrão é:', desvio_padrao)