# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fB6wiZo3sDKwLA5Q3khRwpqvkeGfWr6K
"""

#definindo a temperatura
temp=int(input('Digite  temperatura:'))

if temp < 10:
    print("Está frio!:1)")
elif temp >= 10 and temp < 20:
    print("Está frio, mas dá! :|")
elif temp >= 20 and temp <= 34:
    print("Agora sim")
else:
    print("Está muito quente")