# -*- coding: utf-8 -*-
"""termometroPosto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyBHl9ghaaTJ8yCpAMUesFGf1PWr3OGv
"""

temperatura_normal = 37.2
Consultas = 0

while True:
    termometro = float(input("Qual sua temperatura? "))
    if termometro < temperatura_normal:
        print("Sua temperatura está normal")
        Consultas += 1
        print(f"O número de consultas realizadas na data de hoje é: {Consultas}")
        continuar = input("Deseja outra consulta ? s para sim ou n para não")
        if continuar == 's':
          continue;
        elif continuar == 'n':
          print("Obrigado! Volte Sempre")
          break;
    elif termometro < 38:
        print("Cuidado! Você está em estado Febril")
        Consultas += 1
        print(f"O número de consultas realizadas na data de hoje é: {Consultas}")
        continuar = input("Deseja outra consulta ? s para sim ou n para não")
        if continuar == 's':
          continue;
        elif continuar == 'n':
          print("Obrigado! Volte Sempre")
          break;
    else:
        print("Você está com febre alta")
        Consultas += 1
        print(f"O número de consultas realizadas na data de hoje é: {Consultas}")
        continuar = input("Deseja outra consulta ? s para sim ou n para não")
        if continuar == 's':
          continue;
        elif continuar == 'n':
          print("Obrigado! Volte Sempre")
          break;