# -*- coding: utf-8 -*-
"""Exemplo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Cm0cxfM94j22IdmeO3WLjGfK8QIhJiH
"""

print('Hello World!')