# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rovY5T9yp9TarobAj1wRRuMt-wISVvRB
"""

import numpy as np

#Transposição, rearranjo de um conjunto
#de 15 elementos de 0 a 14.

f=np.arange(15).reshape(3,5)
print(f)

#Matriz transpose

s=f.transpose((0,1))
print(s)

#Criar uma matriz com numeros aleatorios positivos e negativos.

v=np.random.randn(4,4)
print(v)

#Verifica na Array os valores booleanos True e False.
x=(v>0)
print(x)

#Criando a matriz com valores
#-1 e 1 baseados nos valores do array
_# -1 se indentificou como False
# 1 se indentificou como True
z=np.where(x>0,1,-1)
print(z)