# -*- coding: utf-8 -*-
"""py_datascience_aulas 3 em diante_290424.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Cm0cxfM94j22IdmeO3WLjGfK8QIhJiH

aula 3 - 26|04|24
"""

print('Hello World!')

# a sintaxe do for é : for (variavel de controle) in (conjunto)
# = (armazenamento, atribuição)
# == (igual)

numeros = [1, 2, 3, 10, 12]
for numero in numeros:
  if numero == 10:
    break
  print(f"Número : {numero}")
else:
  print ("Acabou")

numeros = [0, 18, 56, 77, 95]
for numero in numeros:
  print(numero)
else:
  print ("Acabou")

#range: Função que gera uma lista de números. (inicio,fim,salto).Inicio 0, salto 1, qdo não informado

for numero in range (20, 30, 2):
  print(numero)

for numero in range (3):
  print (numero)

for numero in range (30,100,10):
  print (numero)

for numero in range (1000000):
  print(numero)
  if numero == 4:
    break
print("Até mais")

"""Atividade 1 : Construa um programa em Python para encontrar todos os números pares entre 1 e 100"""

print(" Os números pares entre 1 e 100 são : ")
for numero in range(2,100,2):
  print(numero)

"""Atividade 2 : Faça um programa em Python (utilizar a estrutura for) que leia 10 valores inteiros e: encontre e mostre o maior valor, encontre e mostre o menor valor, calcule e mostre a média dos números lidos"""

# Ler 10 valores inteiros
valores_inteiros = []
for i in range(10):
    numero = int(input(f"Digite o {i + 1}º número: "))
    valores_inteiros.append(numero)

# Encontrar o maior e o menor valor
maior_valor = max(valores_inteiros)
menor_valor = min(valores_inteiros)

# calcular a média
media = sum(valores_inteiros) / 10

print(f"\nO maior valor é : {maior_valor}")
print(f"\nO menor valor é : {menor_valor}")
print(f"\nA média dos números lidos é : {media:.2f}")

"""Atividade 3 : Faça um programa em python que recebe a temperatura de z clientes e imprima a mensagem de se a temperatura está normal (menor que 37,2 C) ou está em estado febril (37,3 a 38 C) ou com febre (38 C a 39 C) e com febre alta (acima 39 C). no final, mostre a quantidade de pessoas analisadas e a média de temperatura"""

#receber a temperatura e imprimir a mensagem de classificação

temperatura_cliente = float(input("Digite a temperatura em graus C : "))

if temperatura_cliente < 37.2 :
  print("Temperatura Normal")

elif temperatura_cliente >= 37.2 or temperatura_cliente < 38 :
  print("Estado febril")

elif temperatura_cliente >= 38  or temperatura_cliente < 39:
  print("Febre")

elif temperatura_cliente >= 39  :
  print("Febre Alta")

else:
  print("Valor não encontrado")

"""aula 4 - 29|04|24"""

import statistics as st
import math as mt

dados = [10,15,20,25,30,35,40,45,50]

print (f"O conjunto dos dados é: {dados}")
print ("\n")

# média é o valor de centralidade de um conjunto de dados

media = st.mean(dados)

print (f"A média dos dados é: {media:.2f}")
print ("\n")

#mediana é o valor que separa a metade maior e a metade menor de uma amostra

mediana = st.median(dados)

print (f"A mediana dos dados é: {mediana:.2f}")
print ("\n")

# moda é o dado que aparece com maior frequência num conjunto de dados

moda = st.mode(dados)
print (f"A moda dos dados é: {moda:.2f}")





import statistics as st
import math as mt

notas = [7.5,8.2,6.9,9.5,5.8,7.1,8.6,6.3,9.0,8.8]

print (f"O conjunto das notas é: {notas}")
print ("\n")

# média é o valor de centralidade de um conjunto de dados

media = st.mean(notas)

print (f"A média das notas é: {media:.2f}")
print ("\n")

#mediana é o valor que separa a metade maior e a metade menor de uma amostra

mediana = st.median(notas)

print (f"A mediana das notas é: {mediana:.2f}")
print ("\n")

# moda é o dado que aparece com maior frequência num conjunto de dados

moda = st.mode(notas)
print (f"A moda das notas é: {moda:.2f}")

"""# correlação"""

import statistics as st
import math as mt

# tempo de viagem em minutos, coletados com alunos Senai Bras em 29/04
tempo_viagem = [98, 70, 50, 60, 120, 80, 110, 120, 15, 40, 80, 100, 120, 20, 30, 35]

# indice dos meios de transporte
trem = 1
onibus = 2
metro = 3
pe = 4
carro = 5
moto = 6

meio_transporte = [onibus, carro, metro, carro , onibus, onibus, onibus, onibus, pe, moto , onibus, onibus, onibus, pe, pe, pe]


#calculando a mediana do tempo que os alunos levam para chegar à escola Senai Brás

mediana = st.median(tempo_viagem)

print (f"A mediana dos tempos de viagem é: {mediana:.2f} minutos")
print ("\n")

# calculando a média do tempo que os alunos levam para chegar à escola Senai Brás

media = st.mean(tempo_viagem)

print (f"A média do tempo de viagem é: {media:.2f} minutos")
print ("\n")

# moda é o tempo que aparece com maior frequência no deslocamento dos alunos

moda = st.mode(tempo_viagem)
print (f"A moda das notas é: {moda:.2f} minutos ")
print ("\n")

#calculando a correlação entre o tempo de viagem e o meio de transporte
correlacao = st.correlation(tempo_viagem, meio_transporte)

#exibindo o resultado de correlação
print("A correlação entre o tempo de viagem em minutos e o meio de transporte é:", correlacao)

