# -*- coding: utf-8 -*-
"""Dataframe_projetofinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gknlbOw-d5PBYVyYp6s8uv8_IxDcgNVz

# Importando bibliotecas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics as st

"""# Importando Base de dados e transformando em um DataFrame"""

df = pd.read_excel('arquivo_bom.xlsx')
df

"""# Eliminando linhas com o vencimento zerado"""

df.drop(df[df['VENCIMENTOS'] == 0].index, inplace=True)
# df=df.drop(df[df['VENCIMENTOS'] == 0].index)

"""# Fazendo o gráfico"""

# Suponha que você tenha um DataFrame chamado 'df' com duas colunas que deseja plotar
df1 = df.iloc[:, [7,8]]

# Plotando as barras para 'Valor1'
plt.bar(df1['NASCIMENTO'], df1['VENCIMENTOS'], width=1, label='Salário', align='center')


# Adicionando título e rótulos
plt.title('Gráfico de Barras')
plt.xlabel('Ano de Nascimento')
plt.ylabel('Valores')

# Adicionando legenda
plt.legend()

# Exibindo o gráfico
plt.show()

"""# Moda dos salários"""

moda_dos_salarios=st.mode(df1['VENCIMENTOS'])
moda_dos_salarios

"""# Mediana dos salários"""

mediana_dos_salarios=st.median(df1['VENCIMENTOS'])
mediana_dos_salarios

"""# Média dos salários"""

medias_dos_salarios=np.mean(df1['VENCIMENTOS'])
medias_dos_salarios

"""# Variância dos salários"""

# identificando que a dispersão dos valores desta base é imensa.
desvio_padrao = st.stdev(df1['VENCIMENTOS'])
desvio_padrao