# -*- coding: utf-8 -*-
"""Atividade Kart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8wpsXiFQVC4t5VsvUYERRq68JLrjIy2
"""

import numpy as np

# UMA PISTA DE KART PERMITE 10 VOLTAS PARA CADA UM DE 6 CORREDORES.
# FAÇA UM PROGRAMA QUE LEIA OS NOMES E OS TEMPOS (EM SEGUNDOS) DE CADA VOLTA DE CADA CORREDOR
# AO FINAL ,O PROGRAMA DEVE INFORMAR:
# QUEM FEZ A MELHOR VOLTA DA PROVA, E EM QUE VOLTA.
# CLASSIFICAÇÃO FINAL EM ORDEM CRESCENTE.
# QUAL FOI A VOLTA COM A MÉDIA MAIS RÁPIDA

PLT_O1 =np.array([60.2,61.3,61.7,63.9,59.9,62.1,58.3,64.1,65.2,62.5])
print(f'Voltas do Piloto 01 - {PLT_O1}')
MVPLT01 = np.mean(PLT_O1)
VMR_PLT_01 = min(PLT_O1)
print(f'Média Volta do Piloto 01: {MVPLT01}')
print(f'Volta mais rápida do Piloto 01: {VMR_PLT_01}')

PLT_O2 =np.array([59.9,57.9,60.1,59.9,67.1,65.6,63.2,62.1,59.9,60.3])
print(f'Voltas do Piloto 01: {PLT_O2}')
MVPLT02 = np.mean(PLT_O2)
VMR_PLT_02 = min(PLT_O2)
print(f'Média Volta do Piloto 01: {MVPLT02}')
print(f'Volta mais rápida do Piloto 01: {VMR_PLT_02}')

PLT_O3 =np.array([60.3,62.1,60.9,61.2,59.9,63.5,62.7,58.9,64.9,56.9])
print(f'Voltas do Piloto 01: {PLT_O3}')
MVPLT03 = np.mean(PLT_O3)
VMR_PLT_03 = min(PLT_O3)
print(f'Média Volta do Piloto 01: {MVPLT03}')
print(f'Volta mais rápida do Piloto 01: {VMR_PLT_03}')

PLT_O4 =np.array([59.9,62.1,64.1,59.9,56.9,67.1,70.1,59.9,62.4,60.1])
print(f'Voltas do Piloto 01: {PLT_O4}')
MVPLT04 = np.mean(PLT_O4)
VMR_PLT_04 = min(PLT_O4)
print(f'Média Volta do Piloto 01: {MVPLT04}')
print(f'Volta mais rápida do Piloto 01: {VMR_PLT_04}')

PLT_O5 =np.array([57.9,63.1,59.9,70.1,64.1,65.1,71.1,61.9,60.1,63.4])
print(f'Voltas do Piloto 01: {PLT_O2}')
MVPLT05 = np.mean(PLT_O5)
VMR_PLT_05 = min(PLT_O5)
print(f'Média Volta do Piloto 01: {MVPLT05}')
print(f'Volta mais rápida do Piloto 01: {VMR_PLT_05}')

PLT_O6 =np.array([59.9,61.9,57.9,67.9,68.9,69.9,70.1,61.1,54.9,53.9])
print(f'Voltas do Piloto 01: {PLT_O6}')
MVPLT06 = np.mean(PLT_O6)
VMR_PLT_06 = min(PLT_O6)
print(f'Média Volta do Piloto 01: {MVPLT06}')
print(f'Volta mais rápida do Piloto 01: {VMR_PLT_06}')

VLT_1 = np.array([60.2,59.9,60.3,59.9,57.9,59.9],np.float16)
print(f'Volta 01 {VLT_1}')
MDVT_01 = np.mean (VLT_1)
print(f'Média Tempo da Volta 01 = {MDVT_01}')

VLT_2 = np.array([61.3,57.9,62.1,62.1,61.3,61.9], np.float16)
print(f'Volta 02 {VLT_2}')
MDVT_02 = np.mean (VLT_2)
print(f'Média Tempo da Volta 02 = {MDVT_02}')

VLT_3 = np.array([61.7,60.1,60.9,64.1,59.9,57.9],np.float16)
print(f'Volta 03 {VLT_3}')
MDVT_03 = np.mean (VLT_3)
print(f'Média Tempo da Volta 03 = {MDVT_03}')

VLT_4 = np.array([63.9,59.9,61.2,59.9,70.1,67.9],np.float16)
print(f'Volta 04 {VLT_4}')
MDVT_04 = np.mean (VLT_4)
print(f'Média Tempo da Volta 04 = {MDVT_04}')

VLT_5 = np.array([59.9,67.1,59.9,56.9,64.1,68.9],np.float16)
print(f'Volta 05 {VLT_5}')
MDVT_05 = np.mean (VLT_5)
print(f'Média Tempo da Volta 05 = {MDVT_05}')

VLT_6 = np.array([62.1,65.6,63.5,67.1,65.1,69.9],np.float16)
print(f'Volta 06 {VLT_6}')
MDVT_06 = np.mean (VLT_6)
print(f'Média Tempo da Volta 06 = {MDVT_06}')

VLT_7 = np.array([58.3,3.2,62.7,70.1,71.1,70.1],np.float16)
print(f'Volta 07 {VLT_7}')
MDVT_07 = np.mean (VLT_7)
print(f'Média Tempo da Volta 07 = {MDVT_07}')

VLT_8 = np.array([64.1,62.1,58.9,59.9,61.9,61.1],np.float16)
print(f'Volta 08 {VLT_8}')
MDVT_08 = np.mean (VLT_8)
print(f'Média Tempo da Volta 08 = {MDVT_08}')

VLT_9 = np.array([65.2,59.9,64.9,62.4,60.1,54.9],np.float16)
print(f'Volta 09 {VLT_9}')
MDVT_09 = np.mean (VLT_9)
print(f'Média Tempo da Volta 09 = {MDVT_09}')

VLT_10 = np.array([62.5,60.3,56.9,60.1,63.4,53.9],np.float16)
print(f'Volta 10 {VLT_10}')
MDVT_10 = np.mean (VLT_10)
print(f'Média Tempo da Volta 10 = {MDVT_10}')

Resultado_Voltas = np.array([VMR_PLT_01,VMR_PLT_02,VMR_PLT_03,VMR_PLT_04,VMR_PLT_05,VMR_PLT_06])


print (f'Volta Mais rápida Piloto 01 {VMR_PLT_01} | Volta Mais rápida Piloto 02 {VMR_PLT_02} | Volta Mais rápida Piloto 03 {VMR_PLT_03} | Volta Mais rápida Piloto 04 {VMR_PLT_04} | Volta Mais rápida Piloto 05 {VMR_PLT_05} | Volta Mais rápida Piloto 06 {VMR_PLT_06}')

print(Resultado_Voltas)

VMR = sorted (Resultado_Voltas)


print (f'{VMR} = A Volta mais rápida foi do Piloto 06 com a Marca de 53.9 na Volta de nº 10')