# -*- coding: utf-8 -*-
"""ATIVIDADE PANDAS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nN7lGfqgG2Iw5ae2KZKbCvk7bZkriN-
"""

import pandas as pd
file_name = 'video_games1.csv'
df =pd.read_csv(file_name)

nome_jogo = input('Digite o nome do jogo:')
jogos_localizados = df[(df['Title'].str.contains(nome_jogo,case = False))]
if not jogos_localizados.empty:
  display ('Jogos localizados:')
  display (jogos_localizados['Title'])
else:
  display('Nenhum jogo localizado com o nome informado.')