# -*- coding: utf-8 -*-
"""Aula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhZ2wF5phRy5yL-ieXT9yvMtnzapBdfO
"""

#Definindo a temperatura
temp=int(input('Digite a temperatura: '))

#Avaliar se a temperatura está ok
if temp <10:
  print('Está frio! :(')
elif temp >=10 and temp <20:
  print('Está frio, mas dá! :|')
elif temp >=20 and temp <27:
  print('Agora sim! :)')
else:
  print('Está muito quente')

"""Topo da pirâmide (última etapa) => Configuração |
Intermediária => Interação com o usuário |
Base da pirâmide => Teste do algoritmo |

"""

#Definição da temperatura
temp=int(input('Insira a temperatura desejada: '))

#Avaliação

"""**Exercício 2**"""

TotalHoras=float(input('Digite a qtde de horas do Curso: '))

TotalFaltas=(TotalHoras*25)/100

print(TotalFaltas)

QtdeFaltas=float(input('Digite a qtde de horas que você faltou: '))

if QtdeFaltas<=TotalFaltas:
  print('Você está aprovado, boa sorte! As faltas permitidas são', TotalFaltas,'.')
else:
  print('Reprovado!')