# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qo-ZqKs7Cswk_e8s7D0C_wZtuicFYFjz
"""

#definindo a temperatura
temp=25
#Avaliar se a temperatura está OK
if temp <10:
  print('está frio!:1)')
elif temp >=10 and temp <20:
  print ()'Está frio mais dá! :|')
elif temp>=20 and temp <27:
  Print('Agora sim')
else:
  print('Está muito quente')