# -*- coding: utf-8 -*-
"""Aula 3 - statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pObqtkr1wuj5dpyp1jatgTfnweOFh0oI

**Exercício 1**
"""

import statistics as st

dados = [10,15,20,25,30,35,40,45,50]

#Media: soma de todos os elementos dividido pelo número de elementos.
media = st.mean(dados)

#Mediana: valor central do conjunto de dados.
mediana = st.median(dados)

#Moda: valor mais repetido do conjunto.
moda = st.mode(dados)

print('Conjunto de Dados:', dados)
print('Média:', media)
print('Mediana:', mediana)
print('Moda:', moda)

"""**Exercício 2**"""

import statistics as st

notas = [7.5,8.2,6.9,9.5,5.8,7.1,8.6,6.3,9.0,8.8]

media = st.mean(notas)

mediana = st.median(notas)

moda = st.mode(notas)

desvio_padrao = st.stdev(notas)

print(media)
print(mediana)
print(moda)
print(desvio_padrao)

"""**Exercício 3**"""

import statistics as st

horas_estudo = [5,7,3,8,6,4,9,5,7,6]

notas = [75,85,60,90,80,70,95,75,85,80]

correlacao = st.correlation(horas_estudo,notas)
print(correlacao)