# -*- coding: utf-8 -*-
"""CalcSomatoria&Temperatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179ibwz50OJh6ZixLIuJ70IJZiARy34Ey

Francis Codes
april 24 wednesdey 2024
"""

#imprimir
print('Hello World')

a=1

b=2

print (a+b)

c='Rashidi'

print('O Resultado é: ', a+b, 'e seu nome é: ', c)

#Definindo a temperatura
temp=25

#inserting var user
temp=int(input('Digite a Temperatura: '))

#Avaliar se a temperatura está ok
if temp <10:
  print('Está frio! :(')
elif temp >=10 and temp <20:
  print('Está frio mas dá! :|')
elif temp >=20 and temp <27:
  print('Agora sim! :)')
else:
  print('Está muito quente')