# -*- coding: utf-8 -*-
"""Exercicio pandas_entregar ate 15maio .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6lnzvMXU4ODb3wSjmLH623oiuQwEhrb
"""

import pandas as pd

# Carregar o arquivo .csv
quadro_dados = pd.read_csv("video_games1.csv")

# Criar Função para formatar o título do jogo
def formatar_titulo(titulo):
    return titulo.title()

# Criar Função para buscar jogos no arquivo .csv
def buscar_jogos(nome_jogo):
   nome_jogo = nome_jogo.lower()
   quadro_dados_filtrados = quadro_dados[quadro_dados['Title'].str.lower().str.contains(nome_jogo)]
   if quadro_dados_filtrados.empty:
        print("Nenhum jogo encontrado com esse nome.")
   else:
        print()
        print("Jogos encontrados:")
        for index, row in quadro_dados_filtrados.iterrows():
            print()
            print("Nome:", formatar_titulo(row['Title']))
            print("Plataforma:", row['Release.Console'])
            print("Ano:", row['Release.Year'])
            print("Gênero:", row['Metadata.Genres'])
            print("Publicador:", row['Metadata.Publishers'])
            print()

# Solicitar entrada do usuário
nome_jogo = input("Digite o nome (ou parte do nome) do jogo: ")

# Chamar a Função Criada : buscar_jogos
buscar_jogos(nome_jogo)

"""# New Section

# New Section
"""