# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16BC7KS4Itpw_ZxHfgp9nAjBcHCOIQspl
"""

TotalHoras=int(input('Digite a qtd de Horas do Curso: '))

TotalFaltas=(TotalHoras*25)/100

print(TotalFaltas)

QtdeFaltas=float(input ('Digite a qtd de horas vc faltou: '))

if QtdeFaltas<=TotalFaltas:
   print('Voce esta aprovado, boa sorte! As faltas permitidas são',
        TotalFaltas)
else:
   print('Reprovado')