# -*- coding: utf-8 -*-
"""For.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTtzc3mLMc20bUai6LdrFldWkLj1WWRh
"""

#Opções de comando for
numeros=[1,2,3,10,12]
for numero in numeros:
  if numero == 13:
    break
  print(numero)
else:
  print('Acabou!')

"""**Exerício 1**

---
1. Construa um programa em Python utilizando os comandos aprendidos até agora para encontrar todos os números pares entre 1 e 100.
"""

for x in range(0,101,2):
  print(x)

"""**Exercício 2**

---
2. Faça um programa em Python (utilize a estrutura for) que leia 10 valores inteiros e encontre:


*   o maior valor.
*   o menor valor.
*   calcule e mostre a média dos números lidos.





"""

grupo=[3,8,29,67,69,73,74,99,101,180,200,213,220]
interacao10=grupo[:10]
print(interacao10)

grupo_max=max(grupo)
print(grupo_max)

grupo_min=min(grupo)
print(grupo_min)

"""**Exercício 3**

---

3. Faça um programa em linguagem Python que recebe a temperaturade z cliente e imprima a mensagem de se a temperatura está normal (menor que 37,2°C) ou está em estado febril (37,3°C a 38°C) ou com febre (38°C a 39°C) ou ainda se febre alta (acima de 39°C). No final mostre a quantidade de pessoas analisadas e a média de temperatura.
"""

temp=float(input('Insira a temperatura medida: '))

if temp < 37.2:
  print('Sua temperatura está dentro do normal.')
elif temp >= 37.3 and temp < 38:
  print('Atenção, você está febril.')
elif temp >=38.0 and temp <39.1:
  print('Você está com febre!')
else:
  print('Sua febre está alta, procure imediatamente o PS!')

