# -*- coding: utf-8 -*-
"""matriz exercicio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DK8LIPcdlFR8m9nzJqZ2KUeH0SJo-ZQz
"""

import numpy as np

# Nomes dos corredores
nomes_corredores = ["Thaisa", "Felipe", "francis", "joão", "eduardo", "anderson"]

Thaisa=np.array([50,30,55,46,66,43,54,56,60,59])
Felipe=np.array([52,45,44,60,50,48,56,67,76, 58])
francis=np.array([49, 25, 47, 50, 44, 53, 58,60,59,58])
joão=np.array([50,51,52,54,55,57,59,60,58,55])
eduardo=np.array([51,52,53,54,55,54,53,52,51,49])
anderson=np.array([51,52,57,54,55,54,53,52,50,49])

# Matriz de tempos de voltas
tempos_voltas = np.array([Thaisa, Felipe, francis, joão, eduardo, anderson])
print(tempos_voltas)

# Função para encontrar a melhor volta da prova e em qual volta
def melhor_volta(corredores):
    melhor_tempo = np.min(corredores)
    corredor, volta = np.where(corredores == melhor_tempo)
    return corredor[0], volta[0] + 1  # Adicionamos 1 para compensar o índice base 0

# Encontrando a melhor volta da prova
corredor, volta = melhor_volta(tempos_voltas)
print(f"A melhor volta da prova foi de {nomes_corredores[corredor]} na volta {volta} com {tempos_voltas[corredor, volta - 1]} segundos.")

media_voltas = np.mean(tempos_voltas, axis=1)

# Encontrando a volta com a média mais rápida
volta_media_rapida = np.argmin(media_voltas) + 1
print(f"A volta com a média mais rápida foi a volta {volta_media_rapida} com tempo médio de {media_voltas[volta_media_rapida - 1]} segundos.")

"""classificação"""

# Função para imprimir a classificação final em ordem crescente
def classificacao_final(corredores):
    return np.argsort(np.sum(corredores, axis=1)) # Adicionamos 1 para compensar o índice base 0

# Imprimindo a classificação final em ordem crescente
classificacao = classificacao_final(tempos_voltas)
print("Classificação final em ordem crescente:")
for posicao, corredor_idx in enumerate(classificacao):
  print(f"{posicao + 1}. {nomes_corredores[corredor_idx]} - A melhor média foi {media_voltas[corredor_idx]} segundos.")

