# -*- coding: utf-8 -*-
"""moda-media-mediana-desvio_padrao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UH-MqdvjLviJmTH728-4vBuyBCFh8_mA
"""

import statistics as st

notas = [7.5,8.2,6.9,9.5,5.8,7.1,8.6,6.3,9.0,8.8]

media = st.mean(notas)

mediana = st.median(notas)

moda = st.mode(notas)

desvio_padrao = st.stdev(notas)

print(media)
print(moda)
print(mediana)
print(desvio_padrao)