# -*- coding: utf-8 -*-
"""Pesquisa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daF_H70kNTYRyxSh5oK0gC2kWjHuFlo-
"""

import statistics as st

trilhos=6
carro=3
moto=1
onibus=1

tempo=(120, 60, 60, 60, 45, 45, 45,40, 35, 35, 15)


media = st.mean(tempo)
mediana = st.median(tempo)
moda= st.mode(tempo)
desvio = st.stdev(tempo)
trilhos_= mediana/trilhos
carro_= mediana/carro
moto_ = mediana/moto
onibus_= mediana/onibus

print(media)
print(moda)

print(mediana)
print(desvio)


print(trilhos_)
print(carro_)
print(moto_)
print(onibus_)

