# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wF58BdR4-QOGYBT_dLLUHmpaeI1eCfZU
"""

import statistics as st
# Dados de consumo de energia em kWh
consumo_energia = ([20, 25, 30, 35, 40])

# Calculando a média
media = st.mean(consumo_energia)

# Calculando a variância
variancia = st.mean(consumo_energia)

# Exibindo os resultados
print(f"Média do consumo de energia: {media} kWh")
print(f"Variância do consumo de energia: {variancia} kWh^2")

"""# MEDIA"""

def ft_media(lista):
  soma =0
  for i in lista:
    soma = soma + i
  media = soma/len(lista)
  return media

import statistics as st

# Dados do atleta
tempo_atleta = [10, 15, 20, 25, 30]

# Cálculo da média
media = st.mean(tempo_atleta)

# Melhor tempo (o menor tempo)
melhor_tempo = min(tempo_atleta)

# Exibindo os resultados
print(f"O tempo médio da corrida do atleta é: {media}")
print(f"O melhor tempo da corrida do atleta é: {melhor_tempo}")

def melhor_volta_tempos(corredores):
    melhor_corredor = None
    melhor_volta = float('inf')
    for corredor, tempos in corredores.items():
        volta_mais_rapida = min(tempos)
        if volta_mais_rapida < melhor_volta:
            melhor_corredor = corredor
            melhor_volta = volta_mais_rapida
    return melhor_corredor, melhor_volta
    for nome in nomes_corredores:
        tempos = []
        print(f"Digite os tempos das 10 voltas para o corredor {nome}:")
        for volta in range(1, 11):
            tempo = float(input(f"Digite o tempo da {volta}ª volta (em segundos): "))
            tempos.append(tempo)
        corredores[nome] = tempos

    melhor_corredor, melhor_volta = melhor_volta_tempos(corredores)
    print(f"A melhor volta da prova foi do corredor {melhor_corredor}, com {melhor_volta} segundos.")

    volta_media_numero, volta_media = volta_media_rapida(corredores)
    print(f"\nA volta com a média mais rápida foi a volta {volta_media_numero}, com uma média de {volta_media} segundos.")

main()