# -*- coding: utf-8 -*-
"""prefeitura_SPtrans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-G4QEamstb3HTX64PPzffgnp5T-DBkST
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import chardet

# Carregar o arquivo Excel
df=pd.read_excel('sptrans.xlsx')

# Carregar o arquivo Excel em um DataFrame
caminho_do_arquivo = 'sptrans_.xlsx'
df=pd.read_excel('sptrans.xlsx')

# Exibir as primeiras linhas do DataFrame para entender a estrutura dos dados
print(df.head(5))

print(df.columns)
print(df.head())

df.columns = df.columns.str.strip()
fig, ax = plt.subplots()
ax.bar(df['CONTA'], df['ACUMULADO'], width=0.8, edgecolor="white", linewidth=0.7, color='green')
ax.set(xlim=(-0.5, 1.5), xticks=np.arange(2), ylim=(0, 50), yticks=np.arange(0, 55, 5))
plt.title('Receita X Despesas')
plt.xlabel('CONTA')
plt.ylabel('ACUMULADO')

plt.show()