# -*- coding: utf-8 -*-
"""Regressão Linear - Parte 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N601mzZTbYZXpGUurMmWVVYPPfY0Rq4B
"""

#Regressão linear pt.1

import statistics as st
x = [1,2,3,4,5]
y = [2,3,4,5,6]

media_x = st.mean(x)
media_y = st.mean(y)

covariance = sum((x[i]-media_x)*(y[i]-media_y) for i in range(len(x)))
print(covariance)

variance = sum((x[i]-media_x)** 2 for i in range(len(x)))
print(variance)

#Coeficiente de inclinação
b1=covariance/variance

#Coneficiente de intercepto
b0=media_y-b1*media_x

print('O coeficiente de Inclinação é: ',b1)
print('O coeficiente de Intercepto é: ',b0)

#Nova situação

x = [4,5,6,7,8]
y = [14,25,26,17,8]

#função
def linear_regression(x,y):
  n=len(x)
  media_x=st.mean(x)
  media_y=st.mean(y)

  covariancia=sum((x[i]-media_x)*(y[i]-media_y) for i in range(n))
  variancia=sum((x[i]-media_x)** 2 for i in range(n))

  b1=covariancia/variancia
  b0=media_y-b1*media_x

  return b0,b1

#Cálculo dos coeficientes da regressão
intercept, slope = linear_regression(x,y)

print('O coeficiente de intercepto é:' , intercept)

print('O coeficiente de inclinação é:' , slope)