# -*- coding: utf-8 -*-
"""regresso linear parte 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0T29QvWMjb4SOTjKqICVf9bSvlO52Ub
"""

import statistics as st

x=[1,2,3,4,5]
y=[2,3,4,5,6]



media_x=st.mean(x)
media_y=st.mean(y)

covariance=sum((x[i]-media_x)*(y[i]-media_y)for i in range(len(x)))
variance=sum((x[i]-media_x)** 2 for i in range(len(x)))

#coeficiente de intercepto
b1=covariance/variance

b0=media_y-b1*media_x

print('o coeficiente de inclinação é:',b1)

print('o coeficiente de inclinação é:',b0)

print('está quase lá!')