# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8_2T2IeD_bvDttC8cHSXyZ129NftG3C
"""



temp=int(input('digite a temperatura: '))

if temp <10:
  print ('esta frio! :(')
elif temp >=10 and temp <20:
  print ('esta frio, mais da! : |')
elif temp >=20 and temp <27:
  print('agora sim! :)')
else:
 print ('muito quente')