# -*- coding: utf-8 -*-
"""Temperatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTS17kz7iXcfjlML7qpYXTSYVkvBV4vx
"""

#defininfo temperatura

temp= int(input('Digite a tempertura: '))

#avaliar se a temperatura está ok

if temp<10:
 print('muito frio')
elif temp>=10 and temp<20:
 print('esta frio mas dá')
elif temp>=20 and temp<27:
  print('agora sim')
else:
  print('está muito quente')