# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gGY0Q91E_WDwSnat-peuow6YJnVxge0
"""

#Definindo a temperatura
temp=int (input('Digite a temperatura:'))

#Avaliar se a temperatura esta ok
if temp < 10:
  print('Esta frio! :(')
elif temp >=10 and temp <20:
  print('esta frio,mas da! :|')
elif temp >=10 and temp <34:
  print('AGORA SIM!: ')
else:
  print('Esta muito quente')