# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSGAQ4NkRfY9otWUdEJP54Z_uEJWq1fU
"""

TotalHoras=int(input('digite o total de horas no curso: '))

TotalFaltas=(TotalHoras*25)/100

print(TotalFaltas)

QtdFaltas=float(input('digite a quantidade de faltas que vc faltou: '))

if QtdFaltas<=TotalFaltas:
  print('vc esta aprovado, boa sorte as faltas permitifdas são', TotalFaltas)
else:
  print ('Reprovado')

