# -*- coding: utf-8 -*-
"""Atividade6_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/Atividade6_7.ipynb
"""

import statistics as st

#ATV 6 = avaliaçoes de produtos num e-commerce
# 1-5 estrelas

import statistics as st
import random as ran

avaliacoes = [ran.randint(1, 5) for i in range(50)]
print(avaliacoes)

moda_das_avaliacoes = st.mode(avaliacoes)
print('\nModa das avaliaçoes:', moda_das_avaliacoes)

desvio = st.stdev(avaliacoes)
print('Desvio das avaliações: ',desvio)

media = st.mean(avaliacoes)
mediana = st.median(avaliacoes)
print('Média', media)
print('Mediana', mediana)

if media == 1 or media <= 2:
  print('A avaliação média é ruim')
elif media >= 3 or media <= 4:
  print('A avaliação média é mediana')
elif media >= 4 or media == 5:
  print('A avaliação média é boa')

# ATV 7 =  dados de temperatura média (em °C) de uma cidade durante os 7 dias da semana:

import numpy as np

temperaturas = np.array([22.5, 24.0, 19.8, 21.4, 23.0, 25.1, 20.7])
dias = np.array(["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"])
for dia, temp in zip(dias, temperaturas):
    print(f"{dia}: {temp}°C")

# Com base nesses dados, responda:
# Qual foi a temperatura média da semana?
# Qual foi a temperatura máxima e em que dia ocorreu?
# Quais dias tiveram temperatura acima da média?

media_temp = st.mean(temperaturas)
print('A temperatura média da semana foi de: ', media_temp)
indice_max = np.argmax(temperaturas)
maxima_temp = temperaturas[indice_max]
dia_max = dias[indice_max]
print(f'\nA temperatura máxima foi de {maxima_temp}°C no dia {dia_max}')

comparaçao = temperaturas > media_temp
dias_acima_media = dias[comparaçao]
print('Os dias que tiveram temperatura acima da média foram: ', dias_acima_media)

# Crie um novo array com as temperaturas convertidas para Fahrenheit.
# Fórmula: F = C * 1.8 + 32
# Substitua a temperatura de domingo para 22.0°C e recalcule a média.

Fahrenheit = temperaturas * 1.8 + 32
print('As temperaturas em Fahrenheit são: ', Fahrenheit)
for dia, far in zip(dias, Fahrenheit):
    print(f"{dia}: {far}°F")

temperaturas[6:7] = 22
print(temperaturas)

media2 = st.mean(temperaturas)
print('A nova média das temperaturas, com este dado alterado, é: ', media2)