# -*- coding: utf-8 -*-
"""Atividade_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/Atividade_9.ipynb
"""

# Crie uma Series chamada temperaturas com os valores:
# [22, 25, 19, 28, 23] e índices ['Seg', 'Ter', 'Qua', 'Qui', 'Sex'].
# Exiba a Series completa.

import pandas as pd
import numpy as np
import statistics as st

temperaturas = pd.Series([22, 25, 19, 28, 23], index=['Seg', 'Ter', 'Qua', 'Qui', 'Sex'])

temperaturas

# Acesse e exiba o valor da temperatura de 'Qua'.
# Acesse e exiba os valores de temperatura dos dias 'Seg' e 'Sex'.

temperaturas.iloc[0:5:2]

# Manipulação de Valores em Series:
# Altere a temperatura de 'Ter' para 26. Exiba a Series após a alteração.
# Multiplique todos os valores da Series por 1.5. Exiba o resultado.

temperaturas['Ter']=26
print(temperaturas)

temperaturas2=temperaturas*1.5
print(temperaturas2)

# Filtragem e Nulos em Series:
# Exiba apenas as temperaturas que são maiores que 24.
# Crie uma nova Series chamada estoque com os valores:
# [100, 150, np.nan, 80, 120] e índices:
# ['Produto A', 'Produto B', 'Produto C', 'Produto D', 'Produto E'].
# Verifique e exiba quais elementos da Series estoque são nulos.

temperaturas3=temperaturas[temperaturas>24]
temperaturas3

estoque = pd.Series([100, 150, np.nan, 80, 120], index=['Produto A', 'Produto B', 'Produto C', 'Produto D', 'Produto E'])
estoque

estoque.isnull()