# -*- coding: utf-8 -*-
"""ATV1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/ATV1.ipynb
"""

# Primeiro_exercício
import statistics as st

compras_app = [
    55.20, 78.50, 45.00, 120.30, 62.80, 91.00, 88.40, 50.00, 75.10, 105.00,
    60.50, 70.00, 95.00, 110.00, 80.00, 68.20, 59.90, 82.00, 98.70, 72.30,
    130.00, 65.00, 85.00, 77.00, 90.00
]

compras_web = [
    40.00, 60.10, 35.50, 80.00, 52.00, 70.00, 65.80, 48.00, 58.90, 72.00,
    45.50, 55.00, 68.00, 75.00, 63.00, 42.00, 50.00, 60.00, 71.00, 53.00,
    90.00, 49.00, 67.00, 56.00, 69.00, 70.00, 55.00, 62.00, 78.00, 51.00
]

numero_compras_app = len(compras_app)
numero_compras_web = len(compras_web)
print('numero_compras_app', numero_compras_app)
print('numero_compras_web', numero_compras_web)

media_app = st.mean(compras_app)
media_web = st.mean(compras_web)
print('media do app', media_app)
print('media da web', media_web)

mediana_app = st.median(compras_app)
mediana_web = st.median(compras_web)
print('mediana do app', mediana_app)
print('mediana da web', mediana_web)

moda_app = st.mode(compras_app)
moda_web = st.mode(compras_web)
print('moda de data-app', moda_app)
print('moda de data-web', moda_web)

min_app = min(compras_app)
min_web = min(compras_web)
print('minimo de compras app', min_app)
print('minimo de compras web', min_web)

max_app = max(compras_app)
max_web = max(compras_web)
print('maximo de compras app', max_app)
print('maximo de compras web', max_web)

desvio_padrao_app = st.stdev(compras_app)
desvio_padrao_web = st.stdev(compras_web)
print('desvio padrao do app', desvio_padrao_app)
print('desvio padrao da web', desvio_padrao_web)

variancia_app = st.variance(compras_app)
variancia_web = st.variance(compras_web)
print('variancia do app', variancia_app)
print('variancia da web', variancia_web)

