# -*- coding: utf-8 -*-
"""Atv11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oliver22-2/Senai-Python/blob/main/Atv11.ipynb
"""

import numpy as np
import pandas as pd

#Definindo a seed aleatória
np.random.seed(42)

#Gerar os dados
meses = np.arange(1, 13)

#Gerar vendas com distribuição normal e remover negativos
vendas_produto_A = np.random.normal(loc=1000, scale=150, size=12).round().astype(int)
vendas_produto_A = np.where(vendas_produto_A < 0, 0, vendas_produto_A)

vendas_produto_B = np.random.normal(loc=800, scale=100, size=12).round().astype(int)
vendas_produto_B = np.where(vendas_produto_B < 0, 0, vendas_produto_B)

vendas_acessorios = np.random.normal(loc=300, scale=50, size=12).round().astype(int)
vendas_acessorios = np.where(vendas_acessorios < 0, 0, vendas_acessorios)

#Criar o DataFrame
df_vendas = pd.DataFrame({
    'Mês': meses,
    'Produto A': vendas_produto_A,
    'Produto B': vendas_produto_B,
    'Acessórios': vendas_acessorios
})

#Adicionar coluna de Total Vendas Mensal
df_vendas['Total Vendas Mensal'] = (
    df_vendas['Produto A'] + df_vendas['Produto B'] + df_vendas['Acessórios']
)

#Exibir o DataFrame
print("Dados de Vendas Mensais:")
df_vendas

#Calcular médias
medias = df_vendas[['Produto A', 'Produto B', 'Acessórios', 'Total Vendas Mensal']].mean()
print("Média de Vendas por Categoria e Total:")
medias

#Calcular totais acumulados
totais = df_vendas[['Produto A', 'Produto B', 'Acessórios', 'Total Vendas Mensal']].sum()
print("Total de Vendas no Ano por Categoria e Geral:")
totais

#Mês com maior total de vendas
mes_maior_venda = df_vendas.loc[df_vendas['Total Vendas Mensal'].idxmax()]
print("Mês com Maior Venda:")
mes_maior_venda

#Mês com menor total de vendas
mes_menor_venda = df_vendas.loc[df_vendas['Total Vendas Mensal'].idxmin()]
print("Mês com Menor Venda:")
mes_menor_venda