# -*- coding: utf-8 -*-
"""Atv12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oliver22-2/Senai-Python/blob/main/Atv12.ipynb
"""

import matplotlib.pyplot as plt

#Dados de exemplo
meses = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
total_vendas_mensal = [20000, 22000, 25000, 27000, 26000, 29000, 31000, 28000, 30000, 32000, 35000, 36000]
vendas_produtos = {'Produto A': 150000, 'Produto B': 120000, 'Acessórios': 80000}

#Evolução das vendas mensais
plt.figure(figsize=(10, 6))

#Plotando o gráfico de linha
plt.plot(meses, total_vendas_mensal, marker='o', color='b', linestyle='-', linewidth=2, markersize=8)

#Adicionando título e rótulos
plt.title('Evolução das Vendas Mensais da TechGadgets Ltda.', fontsize=14)
plt.xlabel('Mês', fontsize=12)
plt.ylabel('Vendas (R$)', fontsize=12)

#Adicionando grade
plt.grid(True)

#Exibindo o gráfico de linha
plt.show()

#Comparação das vendas totais por categoria de produto
plt.figure(figsize=(10, 6))

#Plotando o gráfico de barras
plt.bar(vendas_produtos.keys(), vendas_produtos.values(), color=['orange', 'green', 'blue'])

#Adicionando título e rótulos
plt.title('Vendas Totais por Categoria de Produto', fontsize=14)
plt.xlabel('Categoria de Produto', fontsize=12)
plt.ylabel('Vendas Totais (R$)', fontsize=12)

#Exibindo o gráfico de barras
plt.show()