# -*- coding: utf-8 -*-
"""Atv2_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/Atv2_5.ipynb
"""

# ATV 2= Calculo de notas:
# <> Media abaixo de 5
# --> REPROVADO
# <> Média entre 5 e 6.9
# --> RECUPERACAO
# <> Média acima de 7
# --> APROVADO
import statistics as st

n1 = input('digite a nota 1: ')
n2 = input('digite a nota 2: ')
n3 = input('digite a nota 3: ')
n4 = input('digite a nota 4: ')
n5 = input('digite a nota 5: ')
media = (float(n1) + float(n2) + float(n3) + float(n4) + float(n5))/5
print(media)
if media < 5:
  print('REPROVADO')
elif media == 5 or media < 6.9:
  print('RECUPERAÇÃO')
elif media == 7 or media > 7.1:
  print('APROVADO')

# ATV 3 = Calculo de media com encerramento em 0
# Crie um programa que irá receber valores, o usuário poderá digitar
# quantos valores ele quiser até ele digitar 0 mostre em tela os valores
# digitados e sua média

valores = []
soma = 0
while True:
    valor = float(input("Digite um valor, digite 0 para sair: "))
    if valor == 0:
        break
    valores.append(valor)
    soma += valor
print("Valores digitados:", valores)
if valores:
    media = soma / len(valores)
    print("Média dos valores:", media)
else:
    print("Nenhum valor foi digitado.")

# ATV 4 e 5 = Moda, Desvio e Variancia
# autoexplicativo demais pra uma descrição

# Lista_de_valores

valores = [ 1 , 7 , 3 , 8 , 6 , 1 , 7 , 7 , 0 , 3 , 6 , 7 , 1 , 7 ,
8 , 0 , 7 , 3 , 1 , 6 , 3 , 1 , 3 , 7 , 6 , 9 , 7 , 7 , 3 , 7 , 0 , 7 , 1 , 7 ,
9 , 35 , 37 , 36 , 34 , 38 , 35 , 37 , 37 , 33 , 36 ,
38 , 37 , 35 , 37 , 34 , 33 , 37 , 36 , 35 , 38 , 36 , 35 , 36 , 37 , 38 ,
39 , 37 , 37 , 36 , 37 , 33 , 37 , 35 , 37 , 39]

moda = st.mode(valores)
print('A moda dos valores é o número', moda)
desvio = st.stdev(valores)
print('\nO desvio padrão dos valores é', desvio)
variancia = st.variance(valores)
print('\nA variancia dos valores é', variancia)