# -*- coding: utf-8 -*-
"""Exemplo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oliver22-2/aula-1/blob/main/Exemplo1.ipynb
"""

import statistics as st
import math as mt

# Geração dos dados
compras_app = [
    55.20, 78.50, 45.00, 120.30, 62.80, 91.00, 88.40, 50.00, 75.10, 105.00,
    60.50, 70.00, 95.00, 110.00, 80.00, 68.20, 59.90, 82.00, 98.70, 72.30,
    130.00, 65.00, 85.00, 77.00, 90.00
]

compras_web = [
    40.00, 60.10, 35.50, 80.00, 52.00, 70.00, 65.80, 48.00, 58.90, 72.00,
    45.50, 55.00, 68.00, 75.00, 63.00, 42.00, 50.00, 60.00, 71.00, 53.00,
    90.00, 49.00, 67.00, 56.00, 69.00, 70.00, 55.00, 62.00, 78.00, 51.00
]

print ('--- Dados Simulados---')
print ('Compras App: ', compras_app)
print ('Compras Web: ', compras_web)
print ('\n')

print ('--- Analise Descitiva Simples---')

tamanho_amostra = len (compras_app)
print ('Tamanho da AmostraApp: ', tamanho_amostra)
tamanho_amostra = len (compras_web)
print ('Tamanho da AmostraWeb: ', tamanho_amostra)

app_vendas = st.mode (compras_app)
print ('App mais vendido: ', app_vendas)
web_vendas = st.mode (compras_web)
print ('Web mais vendido: ', web_vendas)

media_app = st.mean (compras_app)
print ('Média App: ', media_app)
media_web = st.mean (compras_web)
print ('Média Web: ', media_web)

median_app = st.median (compras_app)
print ('Mediana App: ', median_app)
median_web = st.median (compras_web)
print ('Mediana Web: ', median_web)

# App
try:
  celulares_vendas = st.mode(compras_app)
  print (f'Apps mais vendidos', {celulares_vendas})
except st.StatisticsError as e:
  print('Não foi possivel calcula r os apps (erro: {a})')
# Web
try:
  celulares_vendas = st.mode(compras_web)
  print (f'Webs mais vendidos', {celulares_vendas})
except st.StatisticsError as e:
    print('Não foi possivel calcula r os webs (erro: {a})')

desvio_padraoApp = st.stdev(compras_app)
print ('Desvio PadrãoApp: ', desvio_padraoApp)
desvio_padraoWeb = st.stdev(compras_web)
print ('Desvio PadrãoWeb: ', desvio_padraoWeb)

variancia_vendas = st.variance(compras_app)
print ('Variação App: ', variancia_vendas)
variancia_vendas = st.variance(compras_web)
print ('Variação Web: ', variancia_vendas)