# -*- coding: utf-8 -*-
"""Exercicio 12 (Com Matplotlib)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1EhibJ7P-9lg7E2SHQXr0jGy3T5Yw_s
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Gerar dados sintéticos
np.random.seed(42)

meses = np.arange(1, 13)

vendas_produto_A = np.random.normal(loc=1000, scale=150, size=12)
vendas_produto_A = np.where(vendas_produto_A < 0, 0, vendas_produto_A).round()

vendas_produto_B = np.random.normal(loc=800, scale=100, size=12)
vendas_produto_B = np.where(vendas_produto_B < 0, 0, vendas_produto_B).round()

vendas_acessorios = np.random.normal(loc=300, scale=50, size=12)
vendas_acessorios = np.where(vendas_acessorios < 0, 0, vendas_acessorios).round()

# Criar DataFrame
df_vendas = pd.DataFrame({
    'Mês': meses,
    'Produto A': vendas_produto_A,
    'Produto B': vendas_produto_B,
    'Acessórios': vendas_acessorios
})

df_vendas['Total Vendas Mensal'] = df_vendas[['Produto A', 'Produto B', 'Acessórios']].sum(axis=1)

# Gráfico 1: Linha do total de vendas mensais
plt.figure(figsize=(10, 5))
plt.plot(df_vendas['Mês'], df_vendas['Total Vendas Mensal'], marker='o', color='blue')
plt.title('Total Vendas Mensal')
plt.xlabel('Mês')
plt.ylabel('Total de Vendas')
plt.grid(True)
plt.xticks(df_vendas['Mês'])
plt.tight_layout()
plt.show()

# Gráfico 2: Barras comparando vendas dos produtos por mês
plt.figure(figsize=(12, 6))
bar_largura = 0.25
x = np.arange(len(df_vendas['Mês']))

plt.bar(x - bar_largura, df_vendas['Produto A'], width=bar_largura, label='Produto A')
plt.bar(x, df_vendas['Produto B'], width=bar_largura, label='Produto B')
plt.bar(x + bar_largura, df_vendas['Acessórios'], width=bar_largura, label='Acessórios')

plt.title('Vendas por Produto em Cada Mês')
plt.xlabel('Mês')
plt.ylabel('Quantidade Vendida')
plt.xticks(x, df_vendas['Mês'])
plt.legend()
plt.tight_layout()
plt.show()

# Gráfico 3: Pizza  com a distribuição total por categoria
total_categoria = df_vendas[['Produto A', 'Produto B', 'Acessórios']].sum()

plt.figure(figsize=(6, 6))
plt.pie(total_categoria, labels=total_categoria.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribuição Total por Categoria')
plt.axis('equal') # círculo perfeito
plt.tight_layout()
plt.show()

