# -*- coding: utf-8 -*-
"""Exercicio 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULqi5eod7-kalIQrrdHIIqFglZp0H0LP
"""

lista = [
    35 , 37 , 36 , 34 , 38 , 35 , 37 , 37 , 33 , 36 ,
38 , 37, 35 , 37 , 34 , 33 , 37 , 36 , 35 , 38 , 36 , 35 , 36 , 37 , 38 ,
39 , 37 , 37 , 36 , 37 , 33 , 37 , 35 , 37 , 39
]
media = sum(lista) / len(lista)

soma_diferencas = 0
for valor in lista:
    soma_diferencas += (valor - media)

variancia = soma_diferencas / len(lista)

# Cálculo de raiz quadrada sem blibioteca (Método de Newton)
def raiz_quadrada(n, precisao=0.000001):
    estimativa = n / 2
    while abs(estimativa * estimativa - n) > precisao:
        estimativa = (estimativa + n / estimativa) / 2
    return estimativa

desvio_padrao = raiz_quadrada(variancia)

print("Variância:", variancia)
print("Desvio padrão:", desvio_padrao)

