# -*- coding: utf-8 -*-
"""Exercicio 10 ( Criação de Series com pandas)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZc0GhSaEC-iBE2NkGMhllsFeOjYdpqX
"""

import pandas as pd
import numpy as np

# Criação de series de temperaturas
temperaturas = pd.Series([22, 25, 19, 28, 23], index=['Seg', 'Ter', 'Qua', 'Qui', 'Sex'])

# Exibir a SEries completa
print("Temperaturas completas:")
print(temperaturas)

# Acessar e exibir o valor da Temperatura de 'Qua'
print("\nTemperatura de Quata-feira")
print(temperaturas['Qua'])

# Acessar e exibir os valores de Temperatura de "Seg" e "Sex"
print("\nTemperaturas de Segunda e Sexta-feira:")
print(temperaturas[['Seg', 'Sex']])

# Alterar a Temperatura de 'Ter' para 26
temperaturas['Ter'] = 26
print("\nTemperaturas após alterar 'Ter' para 26:")
print(temperaturas)

# Multiplicar todos  os valores das Series por 1.5
multiplicado = temperaturas * 1.5
print("\n'Temperaturas' multiplicadas por 1.5:")
print(multiplicado)

# Exibir apenas as temperaturas maiores que 24
print("\nTemperaturas maiores que 24:")
print(temperaturas[temperaturas > 24])

# Criar a Series estoque com valores e um np.nan
estoque = pd.Series([100, 150, np.nan, 80, 120], index=['Produtos A', 'Produtos B', 'Produtos C', 'Produtos D', 'Produtos E'])

# Verificar e exibir quais elementos da Series estoque são nulos
print("\nElementos nulos em 'estoque':")
print(estoque.isnull())

