# -*- coding: utf-8 -*-
"""Exercicio 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ujc1mFgG1GGAlppyHGxqHJPiRGKQg93b
"""

import statistics as st
import random as rd

# Simulação de 50 avaliaçoes (distribuição realista: mais 4s e 5s)
avaliacoes_produtos = (
    [5]*15 + [4]*12 + [3]*10 + [2]*8 + [1]*5
)

# Embaralhando manualmente (como se fosse aleatório)
avaliacoes_produtos = [
    avaliacoes_produtos[i] for i in [
        12, 0, 23, 5, 9, 33, 45, 27, 18, 3,
        44, 41, 1, 36, 10, 38, 6, 16, 34, 8,
        22, 14, 4, 28, 20, 30, 2, 48, 11, 7,
        26, 29, 37, 21, 17, 43, 24, 40, 35, 19,
        31, 32, 13, 42, 15, 46, 25, 47, 39, 49

      ]
    ]

# Estatísticas
moda = st.mode(avaliacoes_produtos)
media = st.mean(avaliacoes_produtos)
mediana = st.median(avaliacoes_produtos)
desvio_padrao = st.stdev(avaliacoes_produtos)

# Resultados
print("Avaliações (50):", avaliacoes_produtos)
print(f"\nAvaliação mais comum (moda):{moda}")
print(f"Média das avaliações: {media:.2f}")
print(f"Mediana das avaliações: {mediana}")
print(f"Desvio padrão das avaliações: {desvio_padrao:.2f}")

# Interpretação
print("\nInterpretação:")
print(f"- A avaliação mais comum foi {moda}.")
print(f"- A média de {media:.2f} mostra a tendênci geral das avaliações.")
print(f"- A mediana de {mediana} indica o ponto central das notas.")
if desvio_padrao == 0:
    print("- As avaliações foram todas iguais (sem dispersão).")
elif desvio_padrao < 1:
    print("- As avaliações estão concentradas próximas (baixa dispersão).")
else:
    print("- As avaliações estão bem variadas (alta dispersão). ")

