# -*- coding: utf-8 -*-
"""Exercicio 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOwZwP-1Dsgq7BmdOyEUI79m951OBxyV
"""

import numpy as np
import pandas as pd

# Gerar dados sintéticos
np.random.seed(42) # para reprodutibilidade

meses = np.arange(1, 13)


vendas_produtos_A = np.random.normal(loc=1000, scale=150, size=12)
vendas_produtos_A = np.where(vendas_produtos_A < 0, 0, vendas_produtos_A).round().astype(int)

vendas_produtos_B = np.random.normal(loc=800, scale=100, size=12)
vendas_produtos_B = np.where(vendas_produtos_B < 0, 0, vendas_produtos_B).round().astype(int)

vendas_acessorios = np.random.normal(loc=300, scale=100, size=12)
vendas_acessorios = np.where(vendas_acessorios < 0, 0, vendas_acessorios).round().astype(int)

# Criar o DataFrame
df_vendas = pd.DataFrame({
    'Mês': meses,
    'Produto A': vendas_produtos_A,
    'Produto B': vendas_produtos_B,
    'Acessórios': vendas_acessorios
})

# Adicionar coluna Total Vendas Mensal
df_vendas['Total Vendas Mensal'] = df_vendas[['Produto A', 'Produto B', 'Acessórios']].sum(axis=1)

# Exibir o DataFrame
print("Tabela de Vendas:")
print(df_vendas)

# Cálculo das médias
medias = df_vendas[['Produto A', 'Produto B', 'Acessórios', 'Total Vendas Mensal']].sum()
print("\nMédia de Vendas:")
print(medias.round(2))

# Cáculo dos totais acumulados
totais = df_vendas[['Produto A', 'Produto B', 'Acessórios', 'Total Vendas Mensal']].sum()
print("\nTotais Acumulados de Vendas:")
print(totais)

# Mês com maior e menor Total Vendas Mensal
mes_maior_venda = df_vendas.loc[df_vendas['Total Vendas Mensal'].idxmax()]
mese_menor_venda = df_vendas.loc[df_vendas['Total Vendas Mensal'].idxmin()]

print("\nMês com Maior Total de Vendas:")
print(mes_maior_venda)

print("\nMês com Menor Total de Vendas:")
print(mese_menor_venda)

