# -*- coding: utf-8 -*-
"""Exercicios 2 ao 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oliver22-2/Senai-Python/blob/main/Exercicios%202%20ao%205.ipynb
"""

import statistics as st
import math as mt

# programa para calcular a media de 4 notas (exercicio 2)

nota1 = float(input('Digite a nota 1:'))
nota2 = float(input('Digite a nota 2:'))
nota3 = float(input('Digite a nota 3:'))
nota4 = float(input('Digite a nota 4:'))

media = (nota1 + nota2 + nota3 + nota4) / 4

print('A média é:', media)

if media == 7 or media > 7.1:
    print('Aprovado')
elif media == 5 or media < 6.9:
    print('Recuperação')
elif media < 5:
    print('Reprovado')

#Somar valores digitados até o usuário digitar 0 (exercicio 3)
valores = []
soma = 0

while True:
    # Solicita ao usuário que digite um valor
    valor = float(input("Digite um valor (0 para sair): "))

    # Verifica se o valor digitado é zero para encerrar o loop
    if valor == 0:
        break

    # Adiciona o valor à lista e soma para a média
    valores.append(valor)
    soma += valor

# Exibe os valores digitados
print("Valores digitados:", valores)

# Calcula e exibe a média, se houver valores digitados
if valores:
    media = soma / len(valores)
    print("Média dos valores:", media)
else:
    print("Nenhum valor foi digitado.")

#Crie um programa que irá receber a lista de valores abaixo (exercicio 4)

lista_de_valores = [1, 7, 3, 8, 6, 1, 7, 7, 0, 3, 6, 7, 1, 7, 8, 0, 7, 3, 1, 6, 3, 1, 3, 7, 6, 9, 7, 7, 3, 7, 0, 7, 1, 7, 9]

contagem = Counter(lista_de_valores)

moda = contagem.most_common(1)[0][0]
frequencia_moda = contagem.most_common(1)[0][1]

print(f"A moda da lista é:", moda)
print(f"A moda aparece {frequencia_moda} vezes na lista.")

#Crie um programa que receber a lista de valores abaixo (exercicio 5)
lista_de_valores = [35, 37, 36, 34, 38, 35, 37, 37, 33, 36,
                    38, 37, 35, 37, 34, 33, 37, 36, 35, 38, 36, 35, 36, 37, 38,
                    39, 37, 37, 36, 37, 33, 37, 35, 37, 39]

# calcular a variancia
variancia = st.variance(lista_de_valores)

# calcular o desvio padrão
desvio_padrao = st.stdev(lista_de_valores)

print("A variância da lista é:", variancia)
print("O desvio padrão da lista é:", desvio_padrao)