# -*- coding: utf-8 -*-
"""Exercicio 9 (Produção 2) - Aplicações em Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haw-cPXj30DvLA5d7rw4yPWEj6-P9nZx
"""

import numpy as np
import statistics as st
import random as rd

# Garantir reprodutibilidade
np.random.seed(42)
rd.seed(42)

# Produtos e dias
produtos = ['A', 'B', 'C']
dias_semana = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab']

# Tamanho da matriz
num_linha = 3
num_semana = 4
num_dias = len(dias_semana)
num_tipos = len(produtos)

# Inicializar a matriz de produção
producao = np.zeros((num_linha, num_semana, num_dias, num_tipos), dtype=int)

# Preencher com valores aleatórios conforme os intervalos
for linha in range(num_linha):
    for semana in range(num_semana):
        for dia in range(num_dias):
            producao[linha, semana, dia, 0] = rd.randint(50, 100) # Produto A
            producao[linha, semana, dia, 1] = rd.randint(110, 200) # Produto B
            producao[linha, semana, dia, 2] = rd.randint(210, 300) # Produto C

# Exibir a produção
print(producao)

