# -*- coding: utf-8 -*-
"""Exercicio 11 (Criação e Visualização de DataFrames)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vEhXeYG9zbg3QxvXJKhuzpxmp_xhTfAb
"""

import pandas as pd

# Criação do DataFrame
cidades_br = pd.DataFrame({'Cidade':['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre', 'Curitiba'],
                           'Estado':['SP', 'RJ', 'MG', 'RS', 'PR'],
                           'População (milhões)':[12.3, 6.7, 2.5, 1.5, 1.9],
                           'Capital':[True, True, True, True, True]})

# Exiba as 3 primeiras lihas do DataFrame
print("\n3 primeiras linhas:")
print(cidades_br.head(3))

# Exibir 2 linhas aleatórias do DataFrame
print("\n2 linhas aleatórias:")
print(cidades_br.sample(2))

# Acesse e exiba apenas a coluna 'Cidade'
print("\nColuna 'Cidade':")
print(cidades_br['Cidade'])

# Acesse e exiba as colunas 'Estado'e 'População (milhões)'
print("\nColunas 'Estado' e 'População (milhões)':")
print(cidades_br[['Estado', 'População (milhões)']])

# Adicione a nova coluna 'Área (km²)'
cidades_br['Área (km²)'] = [1521, 1200, 331, 496, 435]
print("\nDataFrame com nova coluna 'Área (km²)':")
print(cidades_br)

# Altere os valores da coluna 'Capital' para False em 'Porto Alegre' e 'Curitiba'
cidades_br.loc[cidades_br['Nome da Cidade'].isin(['Porto Alegre','Curitiba']),'É Capital'] = False
print("\nDataFrame com atualização na coluna 'Capital':")
print(cidades_br)

# Renomeie as colunas
cidades_br.columns = ['Nome da Cidade', 'UF', 'Habitantes (M)', 'É Capital', 'Tamanho (km²)']
print("\nDataFrame com colunas renomeadas:")
print(cidades_br)

# Resumo estatísticos das colunas numéricas
print("\nResumo estatístico das colunas numéricas:")
print(cidades_br.describe())

# Exiba cidades com população maior que 2.0 milhões
print("\nCidades com população > 2.0 milhões:")
print(cidades_br[cidades_br['Habitantes (M)'] > 2.0])

# Exclua a coluna 'Tamanho (km²)'
cidades_br.drop(columns=['Tamanho (km²)'], inplace=True)
print("\nDataFrame após exclusão da coluna 'Tamanho (km²)':")
print(cidades_br)

# Exiba a primeira linha usando iloc
print("\nPrimeira linha do DataFrame (iloc):")
print(cidades_br.iloc[0])

# Exiba as linhas de índice 1 a 3 usando iloc
print("\nLinhas de índice 1 a 3:")
print(cidades_br.iloc[1:4])

# Exiba as colunas 'UF' e 'Habitantes (M)' para linhas de índice 0 e 4 usando iloc
print("\nColunas 'UF' e 'Habitantes (M)' para linhas de índice 0 e 4:")
print(cidades_br.iloc[[0, 4]][['UF', 'Habitantes (M)']])

