# -*- coding: utf-8 -*-
"""Exercicio 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIZTuxl4F44PS6C5MHInBnJ4xuaCMLoe
"""

lista = [
1 , 7 , 3 , 8 , 6 , 1 , 7 , 7 , 0 , 3 , 6 , 7 , 1 , 7 ,
8 , 0 , 7 , 3 , 1 , 6 , 3 , 1 , 3 , 7 , 6 , 9 , 7 , 7 , 3 , 7 , 0 , 7 , 1 , 7 ,
9 ,
]

lista = [
    35 , 37 , 36 , 34 , 38 , 35 , 37 , 37 , 33 , 36 ,
38 , 37, 35 , 37 , 34 , 33 , 37 , 36 , 35 , 38 , 36 , 35 , 36 , 37 , 38 ,
39 , 37 , 37 , 36 , 37 , 33 , 37 , 35 , 37 , 39
]

contagem = {}
for num in lista:
  if num in contagem:
    contagem[num] += 1
  else:
    contagem[num] = 1

moda = max(contagem, key=contagem.get)
frequencia = contagem[moda]

print("Moda:", moda)
print("Frequencia:", frequencia)

