# -*- coding: utf-8 -*-
"""Exercicio 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1le0LuNSKdlqCKXdKCjUw2pb0blDqugDa
"""

import statistics as st

# Lista para armazenar as notas
notas = []

# Lista para armazenar as notas
notas = []

# Coleta das 4 notas
for i in range(1, 5):
    nota = float(input(f"Digite a {i}ª nota:"))
    notas.append(nota)

import statistics as st

# Cálculo de média
media = st.mean(notas)

# Exibição das notas e da média
print("\nNotas digitadas:", notas)
print(f"Média: {media:.2f}")

#Verificação da situação do aluno
if media < 5:
    print("Situação: REPROVADO")
elif 5 <= media <= 6.9:
    print("Situação: RECUPERAÇÃO")
else:
    print("Situação: APROVADO")

