# -*- coding: utf-8 -*-
"""Exercicio 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwzUaibUqnKIsJA3JCgRFj7mdj7RhnBR
"""

import statistics as st

# Lista para armazenar os valores
valores = []

print("Digite os valores (digite 0 para parar):")

while True:
    valor = float(input("Digite um valor:"))
    if valor == 0:
        break
    valores.append(valor)

# Verificar se há valores para calcular a média
if valores:
    media = st.mean(valores)
    print("\nValores digitados:", valores)
    print(f"Média: {media:.2f}")
else:
    print("\nNenhum valor foi digitado para calcular a média.")

