# -*- coding: utf-8 -*-
"""Exercicio 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fbKiqsgwATCeek8D6qnfQBYm-pNxif4
"""

lista = [
    35 , 37 , 36 , 34 , 38 , 35 , 37 , 37 , 33 , 36 ,
38 , 37, 35 , 37 , 34 , 33 , 37 , 36 , 35 , 38 , 36 , 35 , 36 , 37 , 38 ,
39 , 37 , 37 , 36 , 37 , 33 , 37 , 35 , 37 , 39
]

media = sum(lista) / len (lista)

soma_diferencas = 0
for valor in lista:
    soma_diferencas += (valor - media)

variancia = soma_diferencas / len(lista)

print("Variância:", variancia)

