# -*- coding: utf-8 -*-
"""Matplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/Matplot.ipynb
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

dias_semana = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"]
temperaturas = [25, 27, 26, 28, 30, 29, 26] # Temperaturas fictícias em °C

plt.plot(dias_semana, temperaturas, marker='o', linestyle='-', color='blue')

plt.xlabel("Dia da Semana")
plt.ylabel("Temperatura (°C)")
plt.title("Variação da Temperatura Semanal")

plt.grid(True)

plt.show()

plt.style.use('_mpl-gallery')

# make data:
x = 0.5 + np.arange(8)
y = [4.8, 5.5, 3.5, 4.6, 6.5, 6.6, 2.6, 3.0]

# plot
fig, ax = plt.subplots()

ax.bar(x, y, width=1, edgecolor="white", linewidth=0.7)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()

plt.style.use('_mpl-gallery')

# make data
y = [4.8, 5.5, 3.5, 4.6, 6.5, 6.6, 2.6, 3.0]

# plot
fig, ax = plt.subplots()

ax.stairs(y, linewidth=2.5)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()