# -*- coding: utf-8 -*-
"""Pandinha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/danielbr20998/Atividades-Senai/blob/main/Pandinha.ipynb
"""

import pandas as pd
import numpy as np
# Incompleto

s1 = pd.Series([1,2,-5,0])

s1

s1.values

s1.index

s2= pd.Series([1,2,-5,0], index=['a','b','c','d'])

s2

s2.index

s2['a']=1000

s2

s2[s2>0]

s2*2

s2.isnull()

dados = {
    'estado': ['SP','MG','PR','SP','MG','PR'],
    'ano': [2023, 2025, 2025, 2024, 2023, 2024],
    'população': [45.9, 21.3, 16.9, 46.6, 24.2, 17.3]
}

df1=pd.DataFrame(dados)

df1

df1.head(2)

df1.tail(2)

df1.sample(2)

df2=pd.DataFrame(dados, columns=['ano','estado','população'])

df2

df2.dtypes

df2.iloc[1:3,[1,2]]

df2