# -*- coding: utf-8 -*-
"""Produção de fábrica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oliver22-2/Senai-Python/blob/main/Produ%C3%A7%C3%A3o%20de%20f%C3%A1brica.ipynb
"""

import numpy as np

# Produção da fábrica
producao = np.array([
    [120, 150, 130],  # Semana 1
    [135, 160, 120],  # Semana 2
    [140, 170, 125],  # Semana 3
    [150, 180, 135],  # Semana 4
    ])

pecas = ['A', 'B', 'C']

# Total de peças produzidas por semana
total_por_semana = np.sum(producao, axis=1)
print("Total por semana:", total_por_semana)

# Produção total de cada tipo de peça
producao_total = np.sum(producao, axis=0)
print("Produção total por peça:", producao_total)

# Semana com maior produção total
semana_maior_producao = np.argmax(total_por_semana) + 1
print("Semana com maior produção total: Semana", semana_maior_producao)

# Média semanal de produção por tipo de peça
media_semanal = np.mean(producao, axis=0)
print("Média semanal de produção por peça:", media_semanal)

# Peça com maior média de produção
peca_maior_media = np.argmax(media_semanal)
print("Peça com maior média de produção:", pecas[peca_maior_media])

# Crescimento percentual semanal da produção da peça A
crescimento_a = np.diff(producao[:, 0]) / producao[:, 0][:-1] * 100
print("Crescimento percentual semanal da peça A:", crescimento_a)

# Semanas em que alguma peça foi produzida abaixo da média
print("Semanas com produção abaixo da média:")
for semana_idx, semana in enumerate(producao):
    for i, valor in enumerate(semana):
        if valor < media_por_peca[i]:
            print(f"Semana {semana_idx+1}: Peça {pecas[i]} ({valor}) < média ({media_por_peca[i]:.2f})")