# -*- coding: utf-8 -*-
"""Temperatura 7 dias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oliver22-2/Senai-Python/blob/main/Temperatura%207%20dias.ipynb
"""

import numpy as np

# Temperaturas dos 7 dias da semana
temperaturas = np.array([22.5, 24.0, 19.8, 21.4, 23.0, 25.1, 20.7])
dias = np.array(["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"])

# Calcular a temperatura média da semana
temp_media = np.mean(temperaturas)
print(f"Temperatura média da semana: {temp_media}°C")

# Temperatura máxima e dia
temp_max = temperaturas.max()
indice_max = temperaturas.argmax()
dia = dias[indice_max]
print(f"Temperatura máxima: {temp_max}°C no dia {dia}")

# Dias acima de média
acima_da_media = temperaturas > temp_media
dias_acima = dias[acima_da_media]
print("Dias com temperatura acima da média:", dias_acima)

# Temperatura  em fahrenheit
fahrenheit = temperaturas*1.8+32
print("Temperaturas em Fahrenheit:", fahrenheit)

#Trocar a temp de domingo para 22°C
temperaturas[6] = 22

#Recalcular nova média
nova_media = temperaturas.mean()
print("Nova média após mudar domingo para 22.0°C:", round(nova_media, 2), "°C")