# -*- coding: utf-8 -*-
"""arquivo Hello Word

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsZqqp2LfCtSFfj1ZemLeOnlWEBWq-Te
"""

print("Hello Word")