# -*- coding: utf-8 -*-
"""AulaTeste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHto9MdEDBN4rHXH4k19Jv4SBT4YHr_C
"""

print('Hello World !! Once again -_-...')