# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LctITU-kX9PJ0CA1UcLHBXqUACEVgCSu
"""

media= float(input("Informa a media: "))
if media >7:
  print("Aprovado")
elif media <5:
    print("Reprovado")
else:
      print("Recuperação")