# -*- coding: utf-8 -*-
"""Compras_sem _juros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttIwzeQ6svqMwn1RU8zFJVEfIMDdhnia
"""

valor_de_compra = float(input('Infome o valor da compra '))
numero_de_prestacoes = int(input('Informe o números de parcelas '))

valor_das_parcelas = valor_de_compra / numero_de_prestacoes

print(float(valor_das_parcelas))

