# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Uo0VxhuQFFuFGIZxAE5xnwI1dGZrnPs
"""

#contagem de 1 a 100
x = 1
while x <=100:
    print(x)
    x = x+1