# -*- coding: utf-8 -*-
"""Contagem números pares - While

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rxxc1kMxPDbbd5bvhfwCLqjiliMPjLg
"""

num = 1
while 1 <= num <= 100:
  if num % 2 == 0:
    print(num)
  num = num + 1