# -*- coding: utf-8 -*-
"""DataScience1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHQiPeDP3I0Y5B456YI6MKaRe4gm7L1N
"""

n1= float(input("digite nota 1: "))
n2= float(input("Digite a nota 2: "))
resultado= (n1+n2)/2

if resultado >=7:
  print('aprovado')
elif resultado <5:
  print('Reprovado')
else:
  print('recuperação')

"""###Desenvolva um programa que recebe do usuário o placar de um jogo de futebol e informa se o resultado foi um empate ou vitória de algum time

"""

Palmeiras= int(input("digite quantos gols o Palmeiras fez: "))
curintia = int(input('digite quantos gols o curintia fez: '))
if Palmeiras > curintia:
  print('Palmeiras ganhou')
elif curintia > Palmeiras:
  print('Curintia ganhou')
else:
  print('Empate')

"""###Faça um algoritmo que receba um valor de uma compra e receba o numero de prestaçoes, apresente o valor das prestações sem juros."""

compra = float(input('Digite o valor da compra:'))
parcela= int(input('Digite o numero de parcelas:'))

prestacao = compra/parcela
print(f'O valor das parcelas é de {prestacao}')

"""###Elabore um algoritmo que dada a idade de um nadador classifique-o em uma das seguintes categorias: Infantil A 5-7 anos, infantil B 8-11 anos,juvenil A 12-13 anos, juvenil B 14 a 17 anos >18"""

idade=int(input('Digite sua idade: '))

if idade <=7:
  print('Infantil A')
elif idade <=11:
  print('Infantil B')
elif idade <=13:
  print('Juvenil A')
elif idade <=17:
  print('Juvenil B')
else:
  print('Maior de idade')

"""### Faça um proframa qye solicite dois números ao usuário (com decimais)Em seguida solicite que o usuário informe o esultado das quatro operações matemáticas (subtração,multi,divisão)"""

num1=float(input('Digite o num1: '))
num2=float(input('digite o num2: '))
operacao=int(input('digite a operação\n 1-Multi\n 2-adição\n 3-sub\n 4-div'))

if operacao==1:
  print(num1 * num2)
elif operacao==2:
  print(num1 + num2)
elif operacao==3:
  print(num1 - num2)
elif operacao==4:
  print(num1/num2)
else:
  print('operação invalida')