# -*- coding: utf-8 -*-
"""DataScience2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFxoq7p4Qknt3LQbkiNXaZfN-wbU4SbA
"""

notas=0
notas_info=0

while True:
   nota = float(input('Digite um número : (-1 para sair)'))
   if (nota ==-1):
     break;
   notas = notas + nota
   notas_info= notas_info + 1
if notas_info>0:
    media= notas/notas_info
    print (f'A quantidade de notas informadas: {notas_info}')
    print(f'Media: {media}')

print (media);

"""### Construa um programa que encontra todos os números de 1 a 100 utilizando while"""

numero= 1

while numero <=100:
  if numero %2==0:
    print(numero)
  numero += 1

"""### Faça um programa em python que leia 10 valores inteiros e encontre o maior e o menor deles e faça a media"""

lista_numeros=[]
contador=0

while contador <3:
  lista_numeros.append(int(input("Ingresse um numero: ")))
  contador=contador+1


print(f'o Maior é:{max(lista_numeros)}')
print(f'O menor é:{min(lista_numeros)}')
print(f'A média é:{sum(lista_numeros)}'/3)

"""### Faça um programa que mede a temperatura n clientes, diga se esta com febre, normal ou febre alta, depois imprima a quantidade de pessoas que foram medidas"""

pessoas=[]
y =1
for temperatura in range (5):
   pessoas.append (input(' digite seu nome:'))
   temperatura= float(input(' informe sua temperatura: '))
   if temperatura <37.2:
     print (' temperatura normal')


   elif temperatura >=37.3 and temperatura ==38:
     print ( ' estado febril !')

   elif temperatura >38 and temperatura <= 39:
     print ( ' com febre !')

   elif temperatura >39 :
     print ( ' febre alta !')

quantidade= len(pessoas)
print(f' o numero de pessoas analisadas foi {quantidade} ')