# -*- coding: utf-8 -*-
"""DataScience3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxaerlj8HyJsIvq50ssdTTgcGSnQ-Tfc

### Ler do teclado a idade e o sexo de n pessoas,calcule e imprima: idade média das mulheres,homens e idade média do grupo
"""

idade_mulheres = []
idade_homens = []
for idade in range(6):
    y=(int ( input(' digite:\n 1-homem ou 2-mulher ')))
    if y == 2:
      idade_mulheres.append(int(input(' digite sua idade:')))
    elif y == 1:
      idade_homens.append(int(input(' digite sua idade:')))
    else:
      print ( ' opcao inexistente !')



print (idade_mulheres)
print (idade_homens)
soma=sum(idade_mulheres)
soma2=sum(idade_homens)
media= soma/3
mediaH= soma2/3


print ( f' a media de idade das mulheres é {media}:')
print (f' a media de idade dos homens é {mediaH}')

"""### Escreva um programa que mostre todos os números de 5 a 100 que são divisíveis por 7, mas não são múltiplos de de 5. Os números obtidos devem ser impressos em sequência"""

numeros = []
for i in range(5,101):
  if i % 7 == 0 and i % 5 != 0:
    numeros.append(i)

print(f'Os números que são divisíveis por 7,mas não são múltiplos de 5, são : {numeros}')

"""### Escreva um programa em python que receba uma string do usuário e mostre de trás pra frente

"""

nome=input('digite seu nome:' )
nome_invertido= nome[::-1]

print(nome_invertido)

"""### Escreva um programa para encontrar qualquer fatorial de qualquer número"""

def fatorial(n):
   if n== 0:
      return 1
   else:
      return n * fatorial (n-1)

num= int (input(' digite um numero:'))
resultado = fatorial (num)

print (f' o fatorial de {num:.2f} é {resultado:.2f}')

"""### Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

