# -*- coding: utf-8 -*-
"""divisiveis7multiplos5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kxy3R1bRsIalnumoS-KyPONuO0CSVjlz
"""

for i in range(5, 101):
    if i % 7 == 0 and i % 5 != 0:
        print(i)