# -*- coding: utf-8 -*-
"""Estatistica_Aula5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qZY3xRNJk6h1FTyQJW-yJGmyjouXlgs
"""

import statistics as st

dados=[10,15,20,25,30,35,40,45,50,15]

# media=statistics.mean

media=st.mean(dados)

print(media)

#Mediana
mediana=st.median(dados)

print(mediana)

#Moda

moda=st.mode(dados)

print(moda)

import statistics as st

notas=[7.5,8.2,6.0,9.5,5.8,7.1,8.6,6.3,9.0,8.8]

media=st.mean(notas)

mediana=st.median(notas)

moda=st.mode(notas)

print(media,mediana,moda)

desvio_padrao=st.stdev(notas)

print(desvio_padrao)

import statistics as at

horas_estudo=[5,7,3,8,6,4,9,5,7,6]

notas=[75,85,60,90,80,70,95,75,85,80]

correlacao=st.correlation(horas_estudo,notas)

print(correlacao)