# -*- coding: utf-8 -*-
"""Operacoes0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7bNXcsujxUVwDGmzA-1U8hpC0wCbOYa
"""

n1 = float(input('Digite o primeiro numero: '))
n2 = float(input('Digite o segundo numero: '))

print(f'A soma entre {n1} + {n2} é: ', n1+n2)
print(f'A subtração entre {n1} - {n2} é: ', n1-n2)
print(f'A multiplicação entre {n1} * {n2} é: ', n1*n2)
print(f'A divisão entre {n1} / {n2} é: ', n1/n2)