# -*- coding: utf-8 -*-
"""temperaturasCSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYjzIHyEEJlL75DKAnLAMS6P-75cVin5
"""

import numpy as np
import statistics as st
import pandas as pd

temperatura = pd.read_csv('temperaturas.csv')
print(temperatura)

medias_temperatura = temperatura.groupby('mes')['temperatura'].mean().reset_index()
print(medias_temperatura)

variancia = np.var(medias_temperatura['temperatura'])
print(variancia)