# -*- coding: utf-8 -*-
"""prestacoes0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ES-MjHC2hEf2oLNKYVcPKO0Z1qczU5cF
"""

print('***Finalize a Sua Compra***')
valor = float(input('DIgite o Valor Final da sua Compra: '))
parcelas = int(input('Digite o numero de parcelas que deseja (até 12): '))

if parcelas > 12:
  print('O Numero de parcelas é invalido!')
else:
  prestacoes = valor/parcelas
  print(f'Sua Compra no valor de {valor}, ficará no valor de {prestacoes} em ' +
   f'{parcelas}x sem juros')