# -*- coding: utf-8 -*-
"""cadastroDeUsuario2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0ennGvVKrOIi3DLk2ZZWXeFSwfBghdi
"""

print('|Realização do Cadastro|')

while True:
  user = input('Digite o nome do usuario: ')
  password = input('Digite a senha da conta: ')

  if user == password:
    print('Nome do usuario não pode ser igual a senha! \nRefaça o cadastro')
  else:
    print('Usuario cadastrado com sucesso! \nSeja Bem-Vindo')
    break