# -*- coding: utf-8 -*-
"""Prestacoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZFFMcS5qzFumztUb4Ks75MvV1kTj7aa
"""

def valorPagamento(prestacao, diasAtraso):
  if float(prestacao) == 0:
    print('Não à mais prestações! \nPrograma Finalizado!')
    return True
  else:
    if int(diasAtraso) == 0:
      print(f'Valor a ser pago: {prestacao}')
    else:
      novoValor = float(prestacao) + (float(prestacao) * (3 + 0.1 * int(diasAtraso)))/100
      print(f'Valor a ser pago com juros: {novoValor}')

while True:
  valorPrestacao = float(input('Digite o valor da sua prestação: '))
  dias = int(input('Sua prestação possui quantos dias de atraso: '))
  if valorPagamento(valorPrestacao, dias):
    break