# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORJtf8n3rMk4KyiU4J_9HTnq0M8Q8wcC
"""

time1 = int(input('Digite o total de gols do Primeiro Time: '))
time2 = int(input('Digite o total de gols do Segundo TIme: '))

if time1 > time2:
  print('Vitoria do Primeiro Time')
elif time2 > time1:
  print('Vitoria do Segundo Time')
else:
  print('Os dois times empataram')