# -*- coding: utf-8 -*-
"""MenorEMaiorComFor2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZwofolRZdtlPqaNZbHGrKvFPNFIkfJY
"""

soma = 0
media = 0

pessoas = int(input('DIgite o numero de pessoas que você quer analisar: '))

for temperaturas in range(pessoas):

  temperatura = float(input('Digite a temperatura: '))

  soma = soma + 1
  media = media + temperatura

  if temperatura < 37.2:
    print('Você não está com febre')
  elif temperatura >= 37.3 and temperatura <= 38:
    print('Você está com estado febril')
  elif temperatura >= 38.1 and temperatura <= 38.9:
    print('Você está com febre')
  else:
    print('Você está com febre alta!')



else:
  print(f'Numero de pessoas analisadas: {soma}')
  print(f'Media das temperaturas analsadas: {media}')
  print('Programa finalizado')