# -*- coding: utf-8 -*-
"""NumerosParesComFor2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp_b2uNWOCyD5X3oqZEiBMt_NaNKaV3T
"""

for numeros in range(101):
  if numeros % 2 == 0:
    print(f'{numeros}')
else:
  print('Programa Finalizado')

