# -*- coding: utf-8 -*-
"""Exercícios de fixação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-AKPRMxJ3en9TTyMCD6iCa8O2gB3WRYh
"""

clube1 = str(input("Informe o nome do primeiro clube: "))
clube2 = str(input("Informe o nome do segundo clube: "))
clube1_gols = int(input("Informe quantos gols o primeiro clube fez: "))
clube2_gols = int(input("Informe quantos gols o segundo clube fez: "))

if clube1_gols == clube2_gols:
  print("Empate")
elif clube1_gols > clube2_gols:
  print("O", clube1, "venceu o", clube2)
else:
  print("O",clube2,"venceu o",clube1)

vlr_total = float(input("Informe o valor da compra: "))
vlr_prest = int(input("Informe o número de prestações: "))
resultado = vlr_total/vlr_prest
print("O valor de cada prestação será de: ",resultado)

idade = int(input("Informe a idade do nadador: "))

if idade < 5:
  print("Nadador sem classificação")
elif 5 <= idade <= 7:
  print("Nadador é Infantil A")
elif 8 <= idade <= 11:
  print("Nadador é Infantil B")
elif 12 <= idade <= 13:
  print("Nadador é Juvenil A")
elif 14 <= idade <= 17:
  print("Nadador é Juvenil B")
else:
  print("Nadador é Adulto")

num1 = float(input("Informe o primeiro número da operação: "))
num2 = float(input("Informe o segundo número da operação: "))
operador = input("Informe o operador desejado (+,-,/,x): ")

if operador == "+":
  res = num1 + num2
  print("O resultado é", res)
elif operador == "-":
  res = num1 - num2
  print("O resultado é", res)
elif operador == "/":
  res = num1 / num2
  print("O resultado é", res)
elif operador == "x":
  res = num1 * num2
  print("O resultado é", res)
else:
  print("Operador inválido")