# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXdPv3epewHoB7wOB2MFFV0ap0NNNZn6
"""

contagem = 10
homens = 0
idadeH = 0
mulheres = 0
idadeM = 0
media = 0

for pessoas in range(contagem):
  sexo = input('Digite o seu sexo \nM -> Mulher \nH -> Homem\n')

  if sexo == 'M':
    idade = int(input('\nDigite a sua Idade: '))
    mulheres = mulheres + 1
    idadeM = idadeM + idade
  elif sexo == 'H':
    idade = int(input('\nDigite a sua Idade: '))
    homens = homens + 1
    idadeH = idadeH + idade
  else:
    print('\nVocê não digitou a letra certa M | H')

  media = media + idade

mediaM = idadeM/mulheres
mediaH = idadeH/homens
mediaG = (idadeH + idadeM)/contagem

print(f'Idade Media das Mulheres: {mediaM}')
print(f'Idade Media dos Homens: {mediaH}')
print(f'Idade Media do Grupo: {mediaG}')

