# -*- coding: utf-8 -*-
"""Exercício de fixação4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Z6TukW-uwiK6XiEv_9RWTOqOq-9AuJZ
"""

num1 = float(input("Informe o primeiro número da operação: "))
num2 = float(input("Informe o segundo número da operação: "))
operador = input("Informe o operador desejado (+,-,/,x): ")

if operador == "+":
  res = num1 + num2
  print("O resultado é", res)
elif operador == "-":
  res = num1 - num2
  print("O resultado é", res)
elif operador == "/":
  res = num1 / num2
  print("O resultado é", res)
elif operador == "x":
  res = num1 * num2
  print("O resultado é", res)
else:
  print("Operador inválido")