# -*- coding: utf-8 -*-
"""Idade0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfKSwofEs48rKMHbuD12sZWPrA0dtIIJ
"""

idade = int(input('Digite a sua idade: '))

if idade >= 5 and idade <= 7:
  print('Você é classificado como "Infantil A"')
elif idade >= 8 and idade <= 11:
  print('Você é classificado como "Infantil B"')
elif idade >= 12 and idade <= 13:
  print('Você é classificado como "Juvenil A"')
elif idade >= 14 and idade <= 17:
  print('Você é classificado como "Juvenil B"')
elif idade > 17:
  print('Você é classificado como "Adulto"')
else:
  print('Você não pode entrar na cliassificação')