# -*- coding: utf-8 -*-
"""CorridaEstatistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgJ2H5PwpUxxRL4az2NIY6MnJUm1go76
"""

import statistics as st

corrida = [10, 15, 20, 25, 30]

media = st.mean(corrida)
moda = st.mode(corrida)

print(media)
print(moda)

