# -*- coding: utf-8 -*-
"""numerosPares0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vw8xdrH2Dgq_anWqI76Qcw2aZ3XDMPEr
"""

numero = 0
while numero <= 100:
  numero = numero + 1

  if numero % 2 == 0:
    print(numero)