# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16MaeGM7rpYypGLrgqZwkgeGuEZA-7Dwo
"""

frase = input('Digite uma frase: ')
frase_inversa = frase[::-1]
print(f'Frase invertida: {frase_inversa}')