# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TIZEMQsgRJdMimcHAP-6ICabPPnnpj6w
"""

qntd_de_pessoas = 0
temperaturas = 0

while True:
  temperatura = float(input('Digite a Temperatura do Seu Corpo: '))

  if temperatura <= 37.2:
    print('Sua temperatura está normal!')
  elif temperatura >= 37.3 and temperatura <= 38:
    print('Você está em estado febril')
  elif temperatura >= 38.1 and temperatura <= 39:
    print('Você está com febre')
  else:
    print('Você está com febre alta')

  qntd_de_pessoas = qntd_de_pessoas + 1
  temperaturas = temperaturas + temperatura

  cont = int(input('Deseja continuar no programa? (Sim = 1 | Não = 0)'))

  if cont == 0:
    break

media = temperaturas/qntd_de_pessoas

print(f'Numero de pessoas analisadas no programa: {qntd_de_pessoas}')
print(f'Medias das temperaturas analisadas: {media}')