# -*- coding: utf-8 -*-
"""varianciaFormula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCClqgOrJTIlCB0nLYhyydRhhQSlq4nV
"""

import statistics as st

x = [1 ,2, 3, 4, 5]
y = [2, 3, 4, 5, 6]

media_x = st.mean(x)
media_y = st.mean(y)

variancia = sum((x[i] - media_x)**2 for i in range(len(x)))
covariancia = sum((x[i] - media_x) * (y[i] - media_y) for i in range(len(x)))

#Coeficiente de Inclinação
b1 = covariancia/variancia

#Coeficiente de Intercepto
b0 = media_y - b1*media_x

print(b1, b0)

