# -*- coding: utf-8 -*-
"""DivisiveisPorSete1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QibZHR2LTJcl_d-KpQcsfAMO-RISG-d
"""

for numero in range(5,101):
  if numero % 7 == 0:
    if numero % 5 != 0:
      print(numero)