# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_etRMUe45eqrmPXCa_zZ1CGVPuJ6Ixf
"""

import pandas as pd
import numpy as np

temperatura = pd.read_csv("temp.csv")
print(temperatura)

medias_por_mes = temperatura.groupby('mes')['temperatura'].mean().reset_index()
print(medias_por_mes)

varianca = np.var(temperatura['temperatura'])
print(varianca)