# -*- coding: utf-8 -*-
"""Variancia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PErr0F9Su3H5beTZvbHEEthr4fbSGpGy
"""

import statistics as st

dados = [20, 25, 30, 35, 40]

variancia = st.variance(dados)

print(variancia)