# -*- coding: utf-8 -*-
"""ImpostoComFunção.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjM0X9r21D2P4Dc3wyf_zB0n7yBBujuN
"""

def somaimposto(taxaImposto, custo):
  valorFinal = custo + (custo * taxaImposto)/100
  return valorFinal

print('Programa Rodando!')
valor = float(input('Digite o valor do produto: '))
taxa = int(input('Digite a porcentagem de imposto: '))
print(f'Valor final do produto com a taxa de {taxa}% será: {somaimposto(taxa, valor)}')