# -*- coding: utf-8 -*-
"""Exercício de fixação2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bivpkHkwesQbx6XgVlJoBlKnOwSHlH03
"""

vlr_total = float(input("Informe o valor da compra: "))
vlr_prest = int(input("Informe o número de prestações: "))
resultado = vlr_total/vlr_prest
print("O valor de cada prestação será de: ",resultado)