# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWzh9Efopamz1SCUqPS3uyWNBormxMlV
"""

def reverso(string):
  print(string[::-1])

string = input('Digite uma palavra')
print('A string ficara assim')
reverso(string)