# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14eO8R2v2GfNjZsbLleJ4rlBbtviae9R-
"""

import statistics as st

x = [1, 2, 3, 4, 5]
y = [2, 3, 4, 5, 6]

def linear_regression(x, y):
  n=len(x)
  mean_x=st.mean(x)
  mean_y=st.mean(y)

  numerador =sum((x[i]-mean_x)*(y[i]-mean_y)for i in range(len(n)))
  denominador =sum((x[i]-mean_x)**2 for i in range(len(n)))

  b1=numerador/denominador
  b0=mean_y-b1*mean_x

  return b0, b1

  intercept, slope = linear_regression(x, y)
  print('O coeficiente de intercepto é (b0):', intercept)
  print('O coeficiente de inclinação é (b1):', slope)