# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_nOElwaXyKzZ2qky1bnmd5yW7SB49RR
"""

import statistics as st
consumo = [20, 25, 30, 35, 40]
media = st.mean(consumo)
varianca = st.variance(consumo)
print(media)
print(varianca)