# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWzh9Efopamz1SCUqPS3uyWNBormxMlV
"""

def fatorial(numero):
  resultado = 1

for i in range  (1, numero + 1):
  resultado *= i
return resultado

