# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j82nxxl-yT6Exq3E_iH4ZvJzh9EbgTsy
"""

import statistics as st

corrida = [10, 15, 20, 25,30]

media = st.mean(corrida)
print(media)

moda = st.mode(corrida)
print(moda)