# -*- coding: utf-8 -*-
"""Hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ctgo7NeXpkCZl9o4C6zZVf8uuLNf2od
"""

print('Hello World')