# -*- coding: utf-8 -*-
"""HelloWorld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rd_mZPN93qfzOVrcJeCAPZpj37ont-7
"""

print('Hello World')