# -*- coding: utf-8 -*-
"""IdadeNadador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NkR0aWk-S4cah8rK3nGeVa4nKIJIQDD
"""

idadenadador = int(input("Qual sua Idade Nadador ? "))

if idadenadador < 5:
    print("Você é muito jovem para competir.")
elif idadenadador >= 5 and idadenadador <= 7:
    print("Sua Categoria é Infantil A")
elif idadenadador >= 8 and idadenadador <= 11:
    print("Sua Categoria é Infantil B")
elif idadenadador >= 12 and idadenadador <= 13:
    print("Sua Categoria é Juvenil A")
elif idadenadador >= 14 and idadenadador <= 17:
    print("Sua Categoria é Juvenil B")
else:
    print("Você é categoria Adulto")