# -*- coding: utf-8 -*-
"""lição 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-oopZfOcoNVTydw3CHGhTciLMkMiVPN
"""

idade = int(input("Digite a idade do nadador: "))

if idade <= 7 :
  print("infantila A")
elif idade <=11:
  print("infantil B")
elif idade <=13:
  print("juvenil A")
elif idade <=17:
  print("juvenil B")
else:
  print("adultos")