# -*- coding: utf-8 -*-
"""Maior, Menor e Média - While

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOJZxclRJl5rTF8pMDWt8fWXjAISNwLY
"""

var = 0
soma = 0
while var <= 9:
  num1 = int(input("Digite um valor inteiro: "))
  if var == 0:
    MaiorValor = num1
    MenorValor = num1
  if num1 > MaiorValor:
    MaiorValor = num1
  elif num1 < MenorValor:
    MenorValor = num1
  soma = soma + num1
  var = var + 1
print("O menor valor digitado é:", MenorValor)
print("O maior valor digitado é:", MaiorValor)
print("A soma dos valores é:", soma)