# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#  dois números solicitado ao usuário e exibe maior e menor numero
numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

if numero1 > numero2:
    maior = numero1
    menor = numero2
elif numero2 > numero1:
    maior = numero2
    menor = numero1
else:
    print("Os números são iguais!")
    exit()

print("O maior número é:", maior)
print("O menor número é:", menor)