# -*- coding: utf-8 -*-
"""Media_metro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tIva04NG2rw4ztidVU3LGX64a2R8EtF
"""

import statistics as st

#Metro/trem
dados= [30,60,90,60,50,150,30,105,105,30,7]

#media
media = st.mean(dados)

print(media)

#mediana
mediana = st.median(dados)

print(mediana)

desvio_padrao=st.stdev(dados)

print(desvio_padrao)