# -*- coding: utf-8 -*-
"""mediaDadosPessoais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-veCnmr2FvGVjnO7m1PalCLylLErExs4
"""

# Inicialização dos contadores e listas para armazenar as idades
contagem_masculino = 0
contagem_feminino = 0
idades_masculino = []
idades_feminino = []

# Loop para solicitar a entrada do usuário 10 vezes
for i in range(10):
    sexo = input("Como você se identifica? Digite M para o sexo masculino ou F para o sexo feminino: ").lower()
    if sexo == "m":
        idade = int(input("Digite sua idade: "))
        print("Sexo Masculino")
        contagem_masculino += 1
        idades_masculino.append(idade)
    elif sexo == "f":
        idade = int(input("Digite sua idade: "))
        print("Sexo Feminino")
        contagem_feminino += 1
        idades_feminino.append(idade)
    else:
        print("Entrada inválida, digite M ou F")

# Calcula a média de idade para cada sexo, se aplicável
if contagem_masculino > 0:
    media_idade_masculino = sum(idades_masculino) / contagem_masculino
    print("Idade média masculina:", round(media_idade_masculino, 2))
else:
    print("Não houve entradas masculinas.")

if contagem_feminino > 0:
    media_idade_feminino = sum(idades_feminino) / contagem_feminino
    print("Idade média feminina:", round(media_idade_feminino, 2))
else:
    print("Não houve entradas femininas.")