# -*- coding: utf-8 -*-
"""media_atleta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItDK3fno5DBwurzRJ5AEX_hJkBcI0UtB
"""

import statistics as st

#tempo medio
x= [10,15,20,25,30]

#media
media = st.mean(x)

print(media)

#melhor tempo
menor= min(x)

print(menor)