# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9pr5CzGZkUhoiepdi6rLflLww7ZptF8
"""

media = int(input("digite a sua nota:"))

if media >= 7:
  print("Você foi aprovado")
elif media < 5:
	print("Reprovado")
else:
	print("você está em recuperacao")