# -*- coding: utf-8 -*-
"""Media_onibus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuRM2pUeRz-uxLBNcJeqdXgiYoUfS_aE
"""

import statistics as st

#Onibus
dados= [90,60,45,80,60,50,150,30,105,105,30,50]

#media
media = st.mean(dados)

print(media)

#mediana
mediana = st.median(dados)

print(mediana)

desvio_padrao=st.stdev(dados)

print(desvio_padrao)