# -*- coding: utf-8 -*-
"""NotaDeAluno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141CHniv8UxzIrCehMG_8R8VE2bIkaXrf
"""

media = float(input("Informe a média:"))
if media > 7:
  print("Aprovado")
elif media < 5:
  print("Reprovado")
else:
  print("Voçê está em Recuperação")