# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-YRulxOxd506r2X0ngxm9trghHPcNfM
"""

import numpy as np

#Matriz (Array) unidimensional
mt=np.array([12,34,26,18,10])

print(mt)

print(type(mt))

#Tipo específico
mtfloat= np.array([1,2,3],dtype=np.float64)

print(mtfloat)

mtint= np.array([1,2,3],dtype=np.int32)

#Mudar tipo de array
mtnew= np.array([1.4,3.6,-5.1,9.42,4.99999])

print(mtnew)

mtnewint= mtnew.astype(np.int32)

print(mtnewint)

mt5= np.array([1,2,3,4])

print(mt5)

mt6= mt5.astype(np.float64)

print(mt6)

#Cria array bidimensional
mt7= np.array([[7,2,23],[12,27,4],[5,34,23]])

print(mt7)

#Vazio tipificados
vazio= np.empty([3,2], dtype= int)

print(vazio)

zeros= np.zeros([4,3])

print(zeros)

zeros= np.ones([5,7])

print(zeros)

diagonal= np.eye(5)

print(diagonal)

ale= np.random.random(5)

print(ale)

#Remover Repetiçõoes
j= np.array([12,12,13,14,11,12,16,20,21])

print(j)

j= np.unique(j)

print(j)

#Criar Bidirecional
k= np.array([[17,22,43], [27,25,14], [15,21,32]])

print(k)

print(k[0] [1])

#menor numero
print(k.min())

#maior numero
print(k.max())

#soma
print(k.sum())

#media
print(k.mean())

#desvio padrão
print(k.std())

#raiz quadrada
print(np.sqrt(k))

#exponecial
print(np.exp(k))