# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yT5Q8ci0zssIzAkp6rsuDBJ3OuCdR7wA
"""

import numpy as np
import statistics as st
import pandas as pd

#Cria uma Serie
s1 = pd.Series([1, 2, -5, 0])
print(s1)

#Mostra o valor da series
s1.values

#Mostra o index (qual o tamanho)
s1.index

#Nomeando os rotulos
s2 = pd.Series([1,2,-5,0], index=['a', 'b', 'c', 'd'])
print(s2)

#Mostrar o index
s2.index

#inputar dados de acordo com uma label
s2['a'] = 1000
s2

#Compraração
s2[s2>0]

#Algebra
s2 * 2

#verificar se é nulo
s2.isnull()

s2.notnull()

#Criar data frame
dados = {'estado': ['SP', 'MG', 'PR', 'SP', 'MG', 'PR'],
         'ano': [2019, 2019, 2020, 2021, 2019, 2020],
         'pop': [45.9, 21.2, 16.7, 46.7, 21.4, 17.3]}

df1 = pd.DataFrame(dados)
df1

#cabeçalho Qtde necessária
df1.head(2)

#verificar o final
df1.tail(2)

#amostra do data frame
df1.sample(3)

#Novo DF a partir do anterior
df2 = pd.DataFrame(dados, columns=['ano', 'estado', 'pop'])
df2

#Mesma coisa
df2['ano']
df2.ano

#Tarefa de casa
#Buscar duas colunas especificas
df2[['estado', 'pop']]

#Usnado iloc
df4 = df2.iloc[2,:]
df4

#Para saber o tipo de cada um
df2.dtypes

#Atribuir valores
df2['estimativa'] = 50
df2

df2['estimativa'] = np.arange(6)
df2

df3 = df2

df3 = df2['ano']
df3

#Deu ruim deleta, outro b.o para resolver
del df2['estimativa']

#forma de deletar
df2.drop('estimativa', axis = 1, inplace=True)

#Entender o DataFrame
df2

df2.shape[0]

#Renomear colunas
df2.columns = ['Ano', 'Estado', 'População']

df2

df2.describe(include = ['ano'])

#Alternar valores !NUNCA USAR ISSO!
df2['Ano'] = df2['Ano'] + 2

df2

df2[df2['Ano'] > 2021]

#Excluir Linhas
df2.drop([0,1])

df2

#Ver dados das linhas
df2.iloc[0]

df2.iloc[1:4,[1,2]]