# -*- coding: utf-8 -*-
"""Placar_do_jogo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-x8a_mnsUGi5mvp6flQBZYKJ__4rUOo
"""

placar_do_jogo = int(input('Insira o placar do jogo '))

Time_a_gols = 5
Time_b_gols = 7

if Time_a_gols == Time_b_gols:
  print ('empate ')
elif Time_a_gols > Time_b_gols:
  print('Time_a é Vencedor ')
else:
  print('Time_b é Vencedor ')

