# -*- coding: utf-8 -*-
"""Placar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtUXxHLMxu6RzIBeEebyy9XaHUDbRUXc
"""

time1 = int(input("Gols Realizados time 1 "))
time2 = int(input("Gols Realizados time 2 "))
if time1 == time2:
  print("O jogo deu Empate")
elif time1 < time2:
  print("O Vencedor foi o time 2 ")
else:
  print("O vencedor foi o time 1 ")