# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Qf5jMRG6UgsGME2HrSzEu6OhogXpz8g
"""

gols_time1= input("Digite o placar: ")
gols_time2= input("Digite o placar: ")

if gols_time1 == gols_time2:
  print("Empate")
elif gols_time1 > gols_time2:
    print("Vitoria do primeiro time")
else:
      print("Vitoria do segundo time")