# -*- coding: utf-8 -*-
"""PlanoDeParcelas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NkR0aWk-S4cah8rK3nGeVa4nKIJIQDD
"""

valorcarro = 10000
plano12vezes = int(valorcarro / 12)
plano24vezes = int(valorcarro / 24)
plano36vezes = int(valorcarro / 36)
parcelas = int(input("Temos planos de parcelas de 12,24,36. Qual Prefere ? "))

if parcelas == 12:
  print("O valor de suas parcelas é de 12 vezes de " + str(plano12vezes))
elif parcelas == 24:
  print("O valor de suas parcelas é de 24 vezes de " + str(plano24vezes))
elif parcelas == 36:
  print("O valor de suas parcelas é de 36 vezes de " + str(plano36vezes))
else:
  print("Infelizmente não temos essa plano de parcelas")