# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mw08XaMAgGgLz6I8NX-LD_CpQwTKB9vr
"""

valor_compra= float(input("Digite o valor da compra R$"))
num_prestacoes= int(input("Digite o numero da prestação: "))

#Calcular o valor de cada prestação
if num_prestacoes == 1:

  valor_prestação = valor_compra
else:
    valor_prestação = valor_compra/num_prestacoes

#Exibe o numero do resultado
print(f"O Valor de cada prestação é R${ valor_prestação:.2f}")