# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9kJaj3A-zguUJIJGZyTGun1KXf3TfzS
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, roc_curve

dados = pd.read_csv('transportetr.csv')
dados.head()

x = dados[['Onibus','Carro','Metro/Obs', 'Moto']]
y = dados['Tempo']

min_max = MinMaxScaler()
min_max.fit(x_train)
x_train_norm = min_max.transform(x_train)
x_test_norm = min_max.transform(x_test)

dados.head()

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

modelo = LinearRegression()
modelo.fit(x_train, y_train)
previsoes = modelo.predict(x_test)

print("Coeficientes de Regressão:")
print(modelo.coef_[0])
print("intercepto")
print(modelo.intercept_)