# -*- coding: utf-8 -*-
"""FirstProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHM5FiM5tgIT89-2caG1neBPVNjbX62Y
"""

print('Hello Word!')

print('hello word!')
print('vamos aprender!')