# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWzh9Efopamz1SCUqPS3uyWNBormxMlV
"""

for numero in range(5, 101):
  if numero % 7 == 0 and 5 != 0:
    print(numero)