# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASUTcbeQJp3HK9WH4FSKWYq5wm36Jc9
"""

media1 = float(input("Por favor, digite a sua idade: "))

if media1 < 7:
    print("Infantil A")
elif media1 >= 7 and media1 < 8:
    print("Infantil B")
elif media1 >= 8 and media1 < 12:
    print("Infantil B")
elif media1 >= 12 and media1 < 14:
    print("Juvenil A")
elif media1 >= 14 and media1 < 16:
    print("Juvenil B")
elif media1 >= 16:
    print("Adultos")