# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASUTcbeQJp3HK9WH4FSKWYq5wm36Jc9
"""

valor_da_compra = float(input("Digite o valor da compra"))
num_prestacoes = int(input("Digite o numero de prestações"))

valor_prestacao = valor_da_compra / num_prestacoes

print("Valor da sua prestação sem juros, é de R$", valor_prestacao)

/