# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASUTcbeQJp3HK9WH4FSKWYq5wm36Jc9
"""

numero1 = float(input("Digite um numero"))
numero2 = float(input("Digite um numero"))
soma = numero1 + numero2
multiplicacao = numero1 * numero2
subtracao = numero1 - numero2
divisao = numero1 / numero2

print("Resultado da Soma:", soma)
print("Resultado da Multiplicação:", multiplicacao)
print("Resultado da Subtração:", subtracao)
print("Resultado da Divisão:", divisao)

/