# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASUTcbeQJp3HK9WH4FSKWYq5wm36Jc9
"""

contar = 1
while contar <= 100:
    print(contar)
    contar += 1