# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FgX9DGWUSM1P3Y9h_qFtMNs2SP3fNHxv
"""

tot_pessoas = 0
soma = 0
qtd_pessoas = int(input("Digite a quantidade de pessoas para analise"))

for pessoa in range(1, qtd_pessoas + 1):
  temperatura = float(input(f"Digite a temperatura da pessoa {pessoa}:"))
  soma += temperatura
  tot_pessoas += 1

if temperatura >= 37.2:
  print("Sua temperatura está normal")
elif temperatura >= 37.3 and temperatura < 38:
  print("Você está em estado febril ")
elif temperatura >= 38 and temperatura < 39:
    print("Você está com febre")
elif temperatura <= 39:
  print("Você está com febre Alta")

  media_temperaturas = soma / tot_pessoas

print(f"total de pessoas analisadas{tot_pessoas}")
print(f"Media da temperatura é {media_temperaturas:2.f} graus")

