# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9pr5CzGZkUhoiepdi6rLflLww7ZptF8
"""

media = int(input("digite a sua nota:"))

if media >= 7:
  print("Você foi aprovado")
elif media < 5:
	print("Reprovado")
else:
	print("você está em recuperacao")

#informar resultado do jogo atraves do resultado digitado pelo usuario

time1= (input("time1 digite o gol:"))
time2= (input("time2 digite o gol:"))
if  time1 >time2:
   print("vitoria do time1 ")
elif time1 == time2:
   print("empate")
else :
   print("vitoria do time2")