# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12akraiIjgZa0H0R0b7HjwECGwb8z9lfo
"""

total_pessoas = 0
soma_temperaturas = 0

while True:
  temperatura = float(input("Digite a temperatura do cliente : "))

  # Limitando a 10 pessoas
  for paciente  in range(10):
    total_pessoas += 1
    soma_temperaturas += temperatura

  if temperatura <37.2:
    print("Estado normal")


  elif 37.3 <= temperatura < 38:
    print("Febril")


  elif 38 < temperatura <= 39:
          print("Com febre")

  else:
          print("Com febre alta.")