# -*- coding: utf-8 -*-
"""Temperatura humana - While

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmqYGibbQcMtFajjsK4Y64M-gTW0n9rA
"""

pacientes = 0
temperatura = 0
soma = 0
while True:
  temperatura = float(input("Digite a temperatura do paciente (para encerrar, digite 0): "))
  if temperatura < 37.2 and temperatura != 0:
    print("O paciente está com a temperatura normal!")
  elif 37.3 <= temperatura <= 38:
    print("O paciente está em estado febril!")
  elif 38.1 <= temperatura <= 39:
    print("O paciente está com febre!")
  elif temperatura > 39 and temperatura !=0:
    print("O paciente está com febre alta!")
  if temperatura == 0:
    break
  pacientes = pacientes + 1
  soma = soma + temperatura
  media = soma/pacientes
print(f"O número de pacientes foi de: {pacientes}")
print(f"A média dos pacientes atendidos foi de: {media}")