# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vm16cLJjxdkLBESEQFDsEsOF0sR3Ad0J
"""

# prompt: print('Ola Mundo')

print('Ola Mundo')