# -*- coding: utf-8 -*-
"""TrabalhoDeCoeficienteDeInclinacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxAlKT26m9Pc0M2aEEqkE2ywZdoE5nFg
"""

import statistics as st

tempoLista = []
transporteLista = []

while True:
  tempo = int(input('Digite o tempo: '))

  if tempo == 0:
    break

  tempoLista.append(tempo)
  transporte = str(input('Digite o transporte: '))
  transporteLista.append(transporte)

onibusTempoLista = []
metroTempoLista = []
motoTempoLista = []
carroTempoLista = []
outroTempoLista = []

for i in range(len(transporteLista)):
  if transporteLista[i] == 'onibus':
    onibusTempoLista.append(tempoLista[i])
  elif transporteLista[i] == 'metro':
    metroTempoLista.append(tempoLista[i])
  elif transporteLista[i] == 'moto':
    motoTempoLista.append(tempoLista[i])
  elif transporteLista[i] == 'carro':
    carroTempoLista.append(tempoLista[i])
  elif transporteLista[i] == 'outro':
    outroTempoLista.append(tempoLista[i])
  else:
    print('não possui/foi digitado errado')

print(onibusTempoLista)
print(metroTempoLista)
print(motoTempoLista)
print(carroTempoLista)
print(outroTempoLista)

def regressao_linear(x, y):
  n = len(x)
  media_x = st.mean(x)
  media_y = st.mean(y)

  numerador = sum((x[i] - media_x)*(y[i] - media_y) for i in range(n))
  denominador = sum((x[i] - media_x)**2 for i in range(n))
  b1 = numerador/denominador
  b0 = media_y - b1*media_x

  return b0, b1

intercepto, inclinacao = regressao_linear(outroTempoLista, onibusTempoLista)
print(f'O coenficiente de intercepto é (b0) da lsita outro é: {intercepto}')
print(f'O coenficiente de inclinação é (b1) da lsita outro é: {inclinacao}')
print('-'*75)
intercepto, inclinacao = regressao_linear(onibusTempoLista, outroTempoLista)
print(f'O coenficiente de intercepto é (b0) da lsita onibus é: {intercepto}')
print(f'O coenficiente de inclinação é (b1) da lsita onibus é: {inclinacao}')