# -*- coding: utf-8 -*-
"""Variancia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daBDjsBOsc593Vn8oanw5jwuM6y3kYxJ
"""

import statistics as st

x= [1,2,3,4,5]
y= [2,3,4,5,6]

#media
media_x = st.mean(x)
media_y = st.mean(y)

st.variance=sum((x[i]-media_x)**2 for i in range(len(x)))

st.covariance=sum((x[i]-media_x) * (y[i]-media_y) for i in range(len(x)))

#Coeficiente de Inclinação
b1= st.covariance/st.variance

#Coeficiente de intercepto
b0= media_y - b1*media_x

print(b0)

print(b1)

import statistics as st

x= [1,2,3,4,5]
y= [2,3,4,5,6]

#Função
def linear_regression(x,y):
  n= len(x)
  mean_x=st.mean(x)
  mean_y=st.mean(y)

  numerador=sum ((x[i]-mean_x) * (y[i]-mean_y) for i in range (len(n)))
  denominator=sum ((x[i]-mean_x) **2 for i in range (len(n)))

  b1=numerador / denominator
  b0=mean_y - b1*mean_x
  return b0, b1

  intercept, slope= linear_regression(x,y)
  print('O coeficiente de intercepto é (b0): ', intercept)
  print('O coeficiente de inclinação é (b1): ', slope)