# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvy95RLD4KQkRHwJQkKM162DMIrStMgQ

#Python Para Data Science
##Msc. Ailton Santos
"""

# Importando as bibliotecas necessárias
import seaborn as sns
import matplotlib.pyplot as plt

# Carregando o conjunto de dados de exemplo do Seaborn
tips = sns.load_dataset("tips")

# Configurando o estilo do Seaborn
sns.set(style="whitegrid")

# Criando um gráfico de dispersão
plt.figure(figsize=(8, 6))
sns.scatterplot(data=tips, x="total_bill", y="tip", hue="sex", style="time", palette="coolwarm")

# Adicionando títulos e rótulos
plt.title("Relação entre Conta Total e Gorjeta para o Funcionário")
plt.xlabel("Conta Total")
plt.ylabel("Gorjeta")

# Exibindo o gráfico
plt.show()