# -*- coding: utf-8 -*-
"""AnaliseDeDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-J7J-7oHJ34En5pcYQKDWpBVsIbEiCs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.preprocessing import MinMaxScaler

dados = pd.read_csv('netflix2.csv')

dados

def classify_rating(rating):
  if rating in['G', 'TV-Y', 'TV-6', 'TV-Y7']:
    return 'Infantil'
  elif rating in ['PG', 'PG-13', 'TV-PG', 'TV-14']:
    return 'Adolescente'
  elif rating in ['R', 'NC-17', 'TV-MA']:
      return 'Adulto'
  else:
      return 'Desconhecido'

#Criando uma coluna(dataframe) com esse nome e aplicando a função criada anteriormente
dados['faixa_etaria'] = dados['rating'].apply(classify_rating)

#Visualização das primeiras linhas
print(dados.head())

#Contagem de filmes baseados pela faixa etaria
contagem_faixa_etaria = dados['faixa_etaria'].value_counts()
print(contagem_faixa_etaria)

#Criação do grafico de barra
plt.figure(figsize=(8, 6))
plt.bar(contagem_faixa_etaria.index, contagem_faixa_etaria.values, color='#a79aff')
plt.xlabel('Faixa Etária')
plt.ylabel('Quantidade de Programas')
plt.title('Distribuição de Programas por Faixa Etária')
plt.show()

#Procurando os generos mais vistos
genero_popular = dados.groupby('faixa_etaria')['listed_in'].value_counts()
print(genero_popular)

#Criando o gráfico de pizza
plt.figure(figsize=(6, 6))
plt.pie(genero_popular.head(10), labels = genero_popular.head(10).index, autopct='%1.1f%%', colors=['#d4afb9', '#d1cfe2', '#9cadce', '#7ec4cf', '#e7ffac', '#ffabab', '#d8ffd6', '#ffccf9', '#c5a3ff', '#ffbebc'])
plt.title('Proporção de Programas por Faixa Etária')
plt.show()

#Pegando os 5 paises que mais assistem a netflix
contagem_paises = dados['country'].value_counts().head(5)
print(contagem_paises)

#Criação do grafico de barra
plt.figure(figsize=(8, 6))
plt.bar(contagem_paises.index, contagem_paises.values, color='#b5b9ff')
plt.xlabel('Faixa Etária')
plt.ylabel('Quantidade de Programas')
plt.title('Distribuição de Programas por Faixa Etária')
plt.show()