# -*- coding: utf-8 -*-
"""lição 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3hV1kJUFPPkT-OKIHyeAG0YrGmTJx_U
"""

v_d_compra = float(input("Digite o numero de compras: "))
prestações = int(input("Digite as prestações: "))
v_p = v_d_compra /prestações
print(f"preço com juros: {v_p}")
juros = v_p * 1/2
if juros / prestações:
  print(f"preço com juros: {juros}")