# -*- coding: utf-8 -*-
"""Projeto Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIPX1K8diaJoQwjFFPgCyWH3vZ6CPZuD
"""

import pandas as pd
import matplotlib.pyplot as plt

casa= pd.read_csv('/content/backhaul.csv.gz')

print(casa)

df1=pd.DataFrame(casa,columns=['sigla_uf ', 'id_municipio ', 'situacao ','ano_atendimento ','concessionaria ','tecnologia ','capacidade_backhaul '])

print(df1)

import matplotlib.pyplot as plt

fig, ax = plt.subplots()

casa= ['blue', 'red', 'orange', 'green', 'gray', 'red','brown']
counts = [10, 20,30,40,50,60,70]
bar_labels  = ['sigla_uf ', 'id_municipio ', 'situacao ','ano_atendimento ','concessionaria ','tecnologia ','capacidade_backhaul ']
bar_colors = ['tab:blue', 'tab:red', 'tab:orange','tab:green','tab:gray','tab:red']
rectangle = plt.Rectangle((1, 2), width=15, height=7)
fontsize = 7

plt.xticks(range(len(bar_labels)), bar_labels, fontsize=fontsize)




ax.bar(casa, counts, label=bar_labels, color=bar_colors)

ax.set_ylabel('Casa')
ax.set_title('Banda Larga')
ax.legend(title='Banda Larga')

plt.show()