# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCKwB_bmIYkQI2tG3I88QQMrDbUkkGRh
"""









import numpy as np

#Operaçoes
n=np.array([[1,2],[3,4]])

print(n)

o = np.array([[1,1],[1,1]])
print(o)

res1=n+o
print(res1)

res2=n*o
print(res2)

q = np.array([2,1])

p=np.array([[2,1]])

print(p)

print(p+q)