# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASUTcbeQJp3HK9WH4FSKWYq5wm36Jc9
"""

soma = 0
contador = 0
maior = ("-inf" )
menor = ( "inf")
while contador < 10:
valor = int(input("Digite um valor"))
soma += valor
contador += 1
if valor > maior
   maior = valor
if valor < menor
   menor = valor
media = soma / 10

print("maior valor:", maior)
print("menor valor:", menor)
print("media é:", media)