# -*- coding: utf-8 -*-
"""while 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_8Ctk8gk0MbGxcWa96DmQkiQLuFjY2E
"""

valor = 0
while True :
  valor = valor + 1
  if valor % 2 == 0:
    print(valor)
  elif valor > 100:
    break