# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRTG8NrSU4M1duuhzmrc9-DlitFZavvc

# Python Para Data Science
## Msc. Ailton Santos

Você trabalha com dados de clientes e quer entender as diferenças no valor de compra entre clientes que usam um aplicativo móvel e clientes que compram apenas pelo site web. Seu objetivo é calcular as estatísticas descritivas para cada grupo e comparar os resultados.

compras_app e compras_web:

Quais conclusões temos sobre?
"""

import statistics

# 1. Geração dos Dados
# Valores de compra simulados (em Reais)
# Clientes que usam o aplicativo:
compras_app = [
    55.20, 78.50, 45.00, 120.30, 62.80, 91.00, 88.40, 50.00, 75.10, 105.00,
    60.50, 70.00, 95.00, 110.00, 80.00, 68.20, 59.90, 82.00, 98.70, 72.30,
    130.00, 65.00, 85.00, 77.00, 90.00
]

# Clientes que usam o site web:
compras_web = [
    40.00, 60.10, 35.50, 80.00, 52.00, 70.00, 65.80, 48.00, 58.90, 72.00,
    45.50, 55.00, 68.00, 75.00, 63.00, 42.00, 50.00, 60.00, 71.00, 53.00,
    90.00, 49.00, 67.00, 56.00, 69.00, 70.00, 55.00, 62.00, 78.00, 51.00
]

print("--- Dados Simulados ---")
print("Compras de Clientes do Aplicativo (primeiras 5):", compras_app[:5])
print("Compras de Clientes da Web (primeiras 5):", compras_web[:5])
print("\n")

# 2. Análise Estatística Descritiva para cada Grupo

print("--- Análise para Clientes do Aplicativo ---")
tamanho_app = len(compras_app)
media_app = statistics.mean(compras_app)
mediana_app = statistics.median(compras_app)
desvio_padrao_app = statistics.stdev(compras_app)
min_app = min(compras_app)
max_app = max(compras_app)

print(f"Número de clientes (App): {tamanho_app}")
print(f"Média das compras (App): R$ {media_app:.2f}")
print(f"Mediana das compras (App): R$ {mediana_app:.2f}")
print(f"Desvio Padrão das compras (App): R$ {desvio_padrao_app:.2f}")
print(f"Compra mínima (App): R$ {min_app:.2f}")
print(f"Compra máxima (App): R$ {max_app:.2f}")
print("\n")

print("--- Análise para Clientes da Web ---")
tamanho_web = len(compras_web)
media_web = statistics.mean(compras_web)
mediana_web = statistics.median(compras_web)
desvio_padrao_web = statistics.stdev(compras_web)
min_web = min(compras_web)
max_web = max(compras_web)

print(f"Número de clientes (Web): {tamanho_web}")
print(f"Média das compras (Web): R$ {media_web:.2f}")
print(f"Mediana das compras (Web): R$ {mediana_web:.2f}")
print(f"Desvio Padrão das compras (Web): R$ {desvio_padrao_web:.2f}")
print(f"Compra mínima (Web): R$ {min_web:.2f}")
print(f"Compra máxima (Web): R$ {max_web:.2f}")
print("\n")

# 3. Comparação e Conclusão

print("--- Comparação e Conclusão ---")

print("Principais observações:")
print(f"- **Média de Compras:**")
print(f"  - App: R$ {media_app:.2f}")
print(f"  - Web: R$ {media_web:.2f}")
print(f"  A média de compras dos clientes do aplicativo é {'maior' if media_app > media_web else 'menor ou igual'} que a dos clientes da web.")

print(f"\n- **Mediana de Compras:**")
print(f"  - App: R$ {mediana_app:.2f}")
print(f"  - Web: R$ {mediana_web:.2f}")
print(f"  A mediana de compras dos clientes do aplicativo é {'maior' if mediana_app > mediana_web else 'menor ou igual'} que a dos clientes da web, o que reforça a tendência central.")

print(f"\n- **Desvio Padrão (Variabilidade):**")
print(f"  - App: R$ {desvio_padrao_app:.2f}")
print(f"  - Web: R$ {desvio_padrao_web:.2f}")
print(f"  O desvio padrão indica que as compras dos clientes do aplicativo têm uma variabilidade {'maior' if desvio_padrao_app > desvio_padrao_web else 'menor ou igual'} em comparação com as compras dos clientes da web.")

print("\n--- Conclusão Geral ---")
print("Analisando as estatísticas descritivas, percebemos que:")
if media_app > media_web:
    print(f"1. Os clientes que utilizam o **aplicativo móvel tendem a realizar compras de valores mais altos**, com uma média de R$ {media_app:.2f} comparada a R$ {media_web:.2f} dos clientes da web.")
else:
    print(f"1. Os clientes que utilizam o **site web tendem a realizar compras de valores mais altos**, com uma média de R$ {media_web:.2f} comparada a R$ {media_app:.2f} dos clientes do aplicativo.")

if desvio_padrao_app > desvio_padrao_web:
    print(f"2. Há uma **maior variabilidade (dispersão)** nos valores de compra entre os clientes do aplicativo (desvio padrão de R$ {desvio_padrao_app:.2f}), sugerindo que alguns clientes do app fazem compras muito grandes, enquanto outros fazem compras menores.")
else:
    print(f"2. Há uma **menor variabilidade (dispersão)** nos valores de compra entre os clientes do aplicativo (desvio padrão de R$ {desvio_padrao_app:.2f}), sugerindo que as compras do app são mais consistentes.")

print("Estas observações descritivas podem guiar decisões de marketing, como investir mais no desenvolvimento do aplicativo ou criar promoções específicas para cada plataforma com base no perfil de compra.")