# -*- coding: utf-8 -*-
"""05_Exercício_Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gwZYNgUAKndGX3ZPsG9FRUUXRV5Ogt_

# Python Para Data Science
## Msc. Ailton Santos

Uma pista de Kart permite 10 voltas para cada um de 6 corredores.
Faça um programa que leia os nomes e os tempos (em segundos) de cada volta de cada corredor. Ao final, o programa deve informar:

-  De quem foi a melhor volta da prova, e em que volta.
- Classificação final em ordem crescente.
- Qual foi a volta com a média mais rápida
"""

import numpy as np

# Número de corredores e voltas
n_corredores = 6
n_voltas = 10

# Leitura dos nomes
nomes = []
print("Digite os nomes dos 6 corredores:")
for i in range(n_corredores):
    nome = input(f"Corredor {i + 1}: ")
    nomes.append(nome)

# Leitura dos tempos (em segundos)
tempos = np.zeros((n_corredores, n_voltas))
print("\nDigite os tempos (em segundos) para cada volta de cada corredor:")
for i in range(n_corredores):
    for j in range(n_voltas):
        tempos[i, j] = float(input(f"Tempo do {nomes[i]} na volta {j + 1}: "))

# 1. Melhor volta da prova
min_tempo = np.min(tempos)
indice_corredor, indice_volta = np.unravel_index(np.argmin(tempos), tempos.shape)
print(f"\nMelhor volta da prova: {nomes[indice_corredor]} na volta {indice_volta + 1} com {min_tempo:.2f} segundos")

# 2. Classificação final por tempo total
tempos_totais = np.sum(tempos, axis=1)
indices_ordenados = np.argsort(tempos_totais)

print("\nClassificação final (ordem crescente de tempo total):")
for pos, idx in enumerate(indices_ordenados, start=1):
    print(f"{pos}º lugar: {nomes[idx]} com tempo total de {tempos_totais[idx]:.2f} segundos")

# 3. Volta com a média mais rápida
medias_por_volta = np.mean(tempos, axis=0)
volta_mais_rapida = np.argmin(medias_por_volta)
print(f"\nVolta com a melhor média de tempo: Volta {volta_mais_rapida + 1} com média de {medias_por_volta[volta_mais_rapida]:.2f} segundos")