# -*- coding: utf-8 -*-
"""SciPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmZ9SQEtxGLzkMNX5KkRyiuIg2v0_Vdz

Resolução de Equação Diferencial:

Definimos a função dydt como a derivada de
𝑦
y em relação a
𝑡
t, representando a equação diferencial
𝑦
′
=
−
2
𝑦
y
′
 =−2y.
Utilizamos solve_ivp para resolver a equação diferencial no intervalo de tempo de 0 a 5.
A solução é plotada usando Matplotlib para visualizar o comportamento de
𝑦
(
𝑡
)
y(t).
Otimização de Função:

Definimos a função f(x) = (x - 3)^2 + 4 que desejamos minimizar.
Usamos minimize com o método BFGS, que é um algoritmo de otimização eficiente para encontrar o valor mínimo da função.
A função imprime o valor mínimo de
𝑓
(
𝑥
)
f(x) e o valor de
𝑥
x onde o mínimo ocorre.
"""

# Primeiro, vamos importar as bibliotecas necessárias
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from scipy.optimize import minimize

# 1. Resolvendo uma Equação Diferencial com SciPy
# Vamos resolver a equação diferencial y' = -2 * y com y(0) = 1

# Definindo a função que representa a derivada de y em relação a t
def dydt(t, y):
    return -2 * y

# Condições iniciais
y0 = [1]  # Valor inicial de y
t_span = (0, 5)  # Intervalo de tempo

# Resolvendo a equação diferencial
solution = solve_ivp(dydt, t_span, y0, t_eval=np.linspace(0, 5, 100))

# Plotando a solução
plt.plot(solution.t, solution.y[0], label="y(t)")
plt.xlabel("Tempo t")
plt.ylabel("y(t)")
plt.title("Solução da Equação Diferencial y' = -2 * y")
plt.legend()
plt.show()

# 2. Otimizando uma Função com SciPy
# Agora, vamos encontrar o mínimo da função f(x) = (x - 3)^2 + 4

# Definindo a função a ser minimizada
def f(x):
    return (x - 3) ** 2 + 4

# Ponto inicial para o algoritmo de otimização
x0 = [0]

# Usando o método 'BFGS' para encontrar o mínimo
result = minimize(f, x0, method='BFGS')

# Exibindo o resultado
print("Valor mínimo de f(x):", result.fun)
print("Valor de x que minimiza f(x):", result.x)

"""Exemplo de Ajuste de Curva e Interpolação com SciPy
Neste exemplo, vamos:

Gerar dados simulados e ajustá-los a uma curva exponencial usando curve_fit da SciPy.
Interpolar os dados usando interp1d para criar uma curva suave entre os pontos.
"""

# Importando bibliotecas necessárias
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.interpolate import interp1d

# 1. Ajuste de Curva (Curve Fitting)
# Gerando dados simulados com ruído
np.random.seed(0)
x_data = np.linspace(0, 4, 50)
y_data = 3 * np.exp(-1.5 * x_data) + np.random.normal(0, 0.2, x_data.size)

# Definindo a função exponencial para ajuste
def exponential_func(x, a, b):
    return a * np.exp(b * x)

# Ajustando a curva aos dados
params, covariance = curve_fit(exponential_func, x_data, y_data, p0=[2, -1])
a_fit, b_fit = params

# Plotando os dados originais e a curva ajustada
plt.scatter(x_data, y_data, label="Dados com Ruído", color="red")
plt.plot(x_data, exponential_func(x_data, a_fit, b_fit), label=f"Curva Ajustada: y = {a_fit:.2f} * exp({b_fit:.2f} * x)", color="blue")
plt.xlabel("x")
plt.ylabel("y")
plt.title("Ajuste de Curva Exponencial")
plt.legend()
plt.show()

# 2. Interpolação (Interpolation)
# Selecionando alguns pontos de dados esparsos
x_sparse = np.linspace(0, 4, 10)
y_sparse = 3 * np.exp(-1.5 * x_sparse)

# Criando a função de interpolação
interp_func = interp1d(x_sparse, y_sparse, kind='cubic')

# Gerando pontos interpolados
x_dense = np.linspace(0, 4, 100)
y_dense = interp_func(x_dense)

# Plotando os pontos esparsos e a interpolação
plt.scatter(x_sparse, y_sparse, label="Pontos Espalhados", color="green")
plt.plot(x_dense, y_dense, label="Interpolação Cúbica", color="purple")
plt.xlabel("x")
plt.ylabel("y")
plt.title("Interpolação Cúbica")
plt.legend()
plt.show()